### ISSUE TITLE
modelplot() add vertical line (e.g. at xintercept = 0) behind estimates

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#101]
It would great to be able to add a vertical line behind the estimates to show the "zero line".
If simply adding a vertical line with ggplot's `geom_vline`, the line will be displayed in front of the estimates. Behind would look much cleaner/nicer.

    library(modelsummary)
    library(kableExtra)
    
    url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
    dat <- read.csv(url)
    
    models <- list()
    models[[1]] <- lm(Crime_prop ~ Literacy, data = dat)
    models[[2]] <- glm(Crime_prop ~ Literacy + Clergy, family = poisson, data = dat)
    models[[3]] <- lm(Crime_pers ~ Literacy, data = dat)
    models[[4]] <- glm(Crime_pers ~ Literacy + Clergy, family = poisson, data = dat)
    names(models) <- c('ols', 'poisson', 'ols', 'poisson')
    

    modelplot(models) +
        geom_vline(xintercept = 0, 
                 color = "orange"
      ) +
      scale_color_manual(values = c("gray10", "gray30", "gray50", "gray70")) +
      theme_classic()

![modelplot](https://user-images.githubusercontent.com/6472717/86106281-a69cc300-bac0-11ea-9134-f1ed8c88a700.png)

**Comment by vincentarelbundock** [comment]
This is an excellent suggestion! Thanks for taking the package out for a spin, and for all the comments and suggestions, I really appreciate it!

It feels like the number of things people may want to add in the background is quite large. Instead of providing a switch to add vertical lines and another switch for annotations, etc, I included an argument called `background`. This accepts a list of 'ggplot2' geoms which are added to the plot *before* `geom_pointrange`. It's already on Github, so if you reinstall and start a new R session, you should have access to it. Here's a somewhat convoluted and ridiculous example:

https://vincentarelbundock.github.io/modelsummary/articles/modelplot.html#background-annotations-1

Does that work for you?

**Comment by vincentarelbundock** [comment]
<img width="868" alt="Screen Shot 2020-06-30 at 08 16 46" src="https://user-images.githubusercontent.com/987057/86125066-0fc50c00-baaa-11ea-8b0c-dd118e0975e4.png">

**Comment by ChrisWaloszek** [comment]
Thank you very much for the quick and positive response! Your hint works like charm! 

    b <- list(geom_vline(xintercept = 0, color = "orange"))
    
    modelplot(models, background = b) +
      scale_color_manual(values = c("gray10", "gray30", "gray50", "gray70")) +
      theme_classic()

![modelplot_b](https://user-images.githubusercontent.com/6472717/86129020-63ebe280-bae2-11ea-89c6-4ce80faaeb5d.png)
