### ISSUE TITLE
msummary() interaction term printing (":" vs " x ")

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#111]
Hey Vincent,

What do you think about functionality that would automatically coerce the ":" in interaction terms to a " x " ($\times$) multiplication sign?

I find that I always do this manually and can't imagine a journal ever preferring the former over the latter for regression tables. Of course, you could always make this optional or override with a custom dictionary.

Just a thought, though ;-)
G

PS. If you're looking for precedent, `fixest::etable()` does this by default. E.g. See [here](https://github.com/lrberge/fixest/issues/11#issuecomment-575653669).

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion! Yep, this makes sense. And the only cases I can think of where this would be inappropriate are super weird. Who gives names like these to their variables?

```r
lm(y ~ `x:z`)
```

There are three issues I need to figure out:

1. For LaTeX output, I use `kable(escape=TRUE)`. I *need* this to be `TRUE`, otherwise whenever someone uses variables with underscores compilation will break. But if I insert `$\\times$`, that will be escaped as well. I could use `X` instead of `\\times`, but that wouldn't be a proper multiplication symbol, and I don't want to piss off the LaTeX zealots.

2. Should `coef_map` names be the ones with `:`, `X`, or should people be allowed to use both (slightly more annoying to implement, but not impossible)? If users refer to the raw table to build their `coef_map`, it probably makes sense to allow them to use both versions.

3. For non-LaTeX output, we need a character which can be displayed in most major typefaces. I'm not 100% sure if the multiplication symbol is supported by system fonts (and others).

Thoughts?

**Comment by vincentarelbundock** [comment]
On 2, maybe it's OK to force people to use the `:` version, if that behavior is documented.

**Comment by grantmcdermott** [comment]
Trust the package maintainer to sweat the details  😂

My thoughts for what they're worth:

1. I could be mistaken, but isn't this one of those cases where you can just sub in the actual [unicode symbol](https://codepoints.net/U+00D7) (i.e. ×) and kable will handle the Pandoc conversion regardless of whether you use the escape option? Testing with a super simple R Markdown example...

```r
---
title: kable test
output: pdf_document
---

```{r kable}
mt = head(mtcars[c(1 ,3, 5), 1:4])
rownames(mt) = gsub(' ', ' × ', rownames(mt))
knitr::kable(mt, "pipe", escape = TRUE)
```

... gives me:

![kabletest](https://user-images.githubusercontent.com/10285037/89349165-9d27ed00-d662-11ea-8ead-c5515e96be46.png)


2. I defer to you here. I'm a fan of flexibility, but totally understand that it might be more pain than it's worth to implement. Documenting it well (as you say) is definitely fair.

3. Hmmm. Again, I'm speaking without full knowledge of the facts but I'm pretty sure the unicode symbol is handled by everything. It certainly works on my system if I change the above R Markdown output to HTML and Word.

**Comment by vincentarelbundock** [comment]
Thanks for looking into it. You're right, character `\u00d7` works for every output format we have (except RTF, for some reason). So that's a super easy solution.

I documented the need to use the `:` version in the `coef_map` docs. I might implement the other way at some point if there's demand (I doubt), but my motivation level for this right now is low.

You can install latest github master if you want to try it out. I'll probably wait for more features or bugfixes before releasing a new version.

**Comment by grantmcdermott** [comment]
Awesome mate. I just tested the dev version and it worked a charm. Really appreciate the quick turnaround.

PS &mdash; I've been adding some long overdue updates to my "regression in R" overview... including refs to and examples from **modelsummary** (e.g. [here](https://raw.githack.com/uo-ec607/lectures/master/08-regression/08-regression.html#Tables)).

**Comment by grantmcdermott** [comment]
(Feel free to close this if you're happy.)

**Comment by vincentarelbundock** [comment]
Oh this page looks really cool. I'll definitely put it on the resources list for the class I'm teaching this fall. And thanks for the `modelsummary` plug. You were right: the x looks sweet in interactions.

BTW, I notice you have some `margins` examples. I have a rewrite of the plotting engine in `ggplot2`. It stood untouched in a PR for about a year (maintainer seems busy), so I spun it off for my own use, but I might make another push to get it merged at some point.

https://github.com/vincentarelbundock/marginsplot
