### ISSUE TITLE
datasummary_skim with variables named Min, Max, Mean, etc.

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#144]
`datasummary_skim` breaks when the dataset includes variables with the same names as the output columns (through `tables::tabular`). But padding is a hack and causes other issues. 

Find a clean way to handle this.

**Comment by sammo3182** [comment]
Not a very relevant problem but of the same object: Is there a shortcut to show the number of observations without missing? 

Also, maybe to document the stat shortcuts in the package would be easier for users to find them, rather than forcing them to dig into the `datasummary_functions.R` in the repo (this might be the wrong way to do this, but what's the correct way to learn the shortcuts)?

**Comment by vincentarelbundock** [comment]
Thanks for the suggestions. I don't want to include all the shortcuts to the manual because they are trivial functions and would polute the manual. However, you're right that they should be more prominent. I listed them in the `datasummary` docstring so you'll see them if you type `?datasummary`.

You can easily reproduce and customize the `datasummary_skim` using `datasummary` and `kableExtra`. For example:

```r
library(modelsummary)
library(kableExtra)

# basic table
dat <- mtcars[, c("vs", "mpg", "hp")]
tab <- datasummary(All(dat) ~ NUnique + Min + Max + SD + Histogram, dat)

# histogram with kableExtra
tab %>%
  kableExtra::column_spec(6, image=spec_hist(as.list(dat), same_lim=FALSE))
```
