### ISSUE TITLE
Error using Lavaan models

### ISSUE THREAD

**Issue by andreaphsz** [vincentarelbundock/modelsummary#146]
When I use ```modelsummary::modelsummary(fit1)```, whereby ```fit1``` is multilevel SEM fitted with lavaan, I get the following error:

```
Fehler in names(OUT) <- object@Data@level.label : 
  Attribut 'names' [2] muss dieselbe Länge haben wie der Vektor [1]
```
Any suggestions?

**Comment by vincentarelbundock** [comment]
Is this model supported by `broom` or `broom.mixed`? What happens when you do this:

```r
library(broom)
library(broom.mixed)
tidy(fit1)
glance(fit1)
```

It would be helpful if you could supply a [Minimal Reproducible Example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

**Comment by andreaphsz** [comment]
```broom::tidy(fit1)``` works, but ```broom::glance(fit1)``` gives the same error...

**Comment by andreaphsz** [comment]
Maybe the problem is the additional warning:
```
Zusätzlich: Warnmeldung:
In lav_fit_measures_check_baseline(fit.indep = fit.indep, object = object) :
  lavaan WARNING: baseline model estimation failed
```

**Comment by vincentarelbundock** [comment]
Thanks for checking!

This means that the problem is at the `broom` level. I see on their github that they recently fixed a problem with the `lavaan` `glance` method. So my recommendation is to update your `broom` install to the latest version from github:

```r
library(remotes)
install_github('tidymodels/broom')
```

Restart `R` completely, and try again.

If that doesn't work, I recommend opening a new issue on the `broom` github.

**Comment by andreaphsz** [comment]
Thank you! I will do so.
