### ISSUE TITLE
modelplot, option exponentiate=TRUE not working

### ISSUE THREAD

**Issue by mcomsa** [vincentarelbundock/modelsummary#158]
Thank you so much for your very useful package. Option "exponentiate=TRUE" produces a warning message. Please check this example:

library(modelsummary)
mod <- glm(am ~ mpg + drat, mtcars, family=binomial)
modelplot(mod)
modelplot(mod, exponentiate=TRUE)

**Comment by vincentarelbundock** [comment]
The problem is that we want to be able to pass arbitrary arguments to the `broom::tidy` function that extracts coefficients, because in some models we want `exponentiate=TRUE`, and in other models we may want something else (i.e., the set of valid arguments for `tidy` is unconstrained). In the same way, we also want to pass arbitrary arguments to the `ggplot2` functions in order to customize the appearance of the plots, as described in the vignette here:

https://vincentarelbundock.github.io/modelsummary/articles/modelplot.html

To do this, we must pass the function's ellipsis (i.e., `...`) to *both* the `broom` and the `ggplot2` packages. But when `ggplot2` encounters an unknown argument, it ignores it and prints a warning.

This warning causes no problem whatsoever. So you can wrap your call in a:

```r
suppressWarnings(modelplot(mod))
```

Eventually, I could potentially introspect the `...` and remove `exponentiate` from the `ggplot2` call. That's doable, but it will take me a bit of time.

**Comment by mcomsa** [comment]
Thank you. Sorry for not being clear. I intended to plot the exponentiated coefficients.

**Comment by vincentarelbundock** [comment]
Oh sorry. It was just a really weird timing because there was a bug that did not allow to exponentiate coefficients, and I fixed that but *yesterday*. If you install the development version from Github, you should be able to exponentiate coefficients (but it will produce a harmless warning):

To install the development version of `modelsummary`:

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Then restart your R session completely to make sure that the changes take effect.

**Comment by mcomsa** [comment]
Thank you so much for your help. A similar issue related to mice was initiated by me via Adi Dusa, so thank you for that too. All the best.
