### ISSUE TITLE
Allow easier robust SE call in modelsummary

### ISSUE THREAD

**Issue by NickCH-K** [vincentarelbundock/modelsummary#183]
I'm in the process of switching my teaching materials from `jtools::export_summs()` to `modelsummary::msummary()`, and the main element I'm missing is the ability to just do `robust = TRUE` or `cluster = 'group'` (or `robust  = 'HC0'` or whatever I want to specify).

I think this would be a very handy addition to `modelsummary()`. Obviously, you already have this functionality with `statistic_override` but IMO it could be a bit easier to use. These new options (`robust` and `cluster`), if specified, would basically just supersede the `statistic_override` option, and set up a properly-formatted `statistic_override` for the user.

I'd be happy to code this up myself if you're open to the idea.

**Comment by vincentarelbundock** [comment]
Glad you're working with `modelsummary`!

And yes, I agree that this could be easier. I imagine that many students won't find the idea of passing a variance-covariance extractor function from the `sandwich` package easy. So I'm all in for making improvements in that area.

The only thing minor issue is that one important design goals is to limit the number of arguments in the main function. The unending list of arguments in alternative packages makes their docs really hard to read, I think, and simplification was one of my main motivations at the very start.

So I'm wondering if there's a way to "overload" the current arguments in a way that feels natural and doesn't complicate things too much. For instance, I could imagine:

```r
modelsummary(mod, statistic_override="HC0")
modelsummary(mod, statistic_override="robust")
```

This would automatically pass an appropriate `sandwich` function to `lmtest::coeftest` for supported models. The whole thing could be implemented by inserting about 4 lines of code here:

**https://github.com/vincentarelbundock/modelsummary/blob/master/R/extract_statistic_override.R#L56**

I don't have a clear sense of how we could achieve the same natural workflow for clustered SEs at the moment. I know `sandwich` accepts a formula where the RHS defined the groups over which to cluster. So maybe these two calls produce the same results?

```r
v = function(x) sandwich::vcovCL(x, ~clustergroup)
modelsummary(mod, statistic_override=v)
modelsummary(mod, statistic_override=~clustergroup)
```

Thoughts?

**Comment by NickCH-K** [comment]
Going for a single argument makes sense to me, and it should be fairly straightforward to detect the syntax and convert appropriately. "`statistic_override`" is a bit opaque (and long) as a name, though. I had read the docs before but didn't actually realize until writing this Issue what `statistic_override` does. **estimatr** uses "`se_type`", that might be a bit clearer in its purpose. `statistic_override` doesn't do anything other than precision statistics, right? "`vcov`" or "`vcov_type`" could also work if you want to be clear it works for t-stats, CIs, etc., as well.

Another way to do clusters would be a quoted variable name, i.e. `statistic_override = 'clustergroup'` or passing a vector. But the one-sided function is probably a touch cleaner, and would pass straight into `vcovCL`.

**Comment by vincentarelbundock** [comment]
Cool. I'll try to implement a first version with the single string or RHS formula idea. I should get to this very soon and will ping you when it's done.

I agree that the `statistic_override` isn't great, for the reasons you point to. I'm not a big fan of `se_type` either, since we can also display confidence intervals, etc. `vcov` might be a good choice, but there's the issue of backward compatibility...

The original vision was to call it "statistic_override" to keep things very general. In principle, people could put whatever they want in that space. For instance, in the latest version (0.6.4, on CRAN just now), you can use `glue` strings to do fancy stuff like replacing p-values by smiley faces, using a rule that is automatically adjusted with robust standard errors if you want. (Yeah, i realize this is silly.)

``` r
library(modelsummary)

mod = lm(vs ~ mpg + hp + drat, mtcars)
modelsummary(
  mod,
  statistic = c("conf.int",
                "se = {std.error}",
                "{ifelse(p.value < 0.1, '😊', '☹️')}"),
  statistic_override = sandwich::vcovHC,
  output = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Model 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">0.465</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[-1.022, 1.953]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">se = 0.726</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">☹️</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpg</td>
<td style="text-align: center;">0.018</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[-0.027, 0.062]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">se = 0.022</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">☹️</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hp</td>
<td style="text-align: center;">-0.004</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[-0.008, 0.000]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">se = 0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">😊</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drat</td>
<td style="text-align: center;">0.054</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">[-0.337, 0.444]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">se = 0.191</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">☹️</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.551</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.503</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">30.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">37.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-10.156</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">11.460</td>
</tr>
</tbody>
</table>

**Comment by NickCH-K** [comment]
Ha - I do always at least appreciate the *possibility* of doing stuff like that. 

I do see the point that an argument name like `se_type` would be confusing when applied to CIs. As for backwards compatibility, one option is to change the option name to `vcov` (or something), and then in the function check `list(...)` for a `statistic_override` option. If it finds it, overwrite the `vcov` argument with it. This maintains the ability to use `statistic_override` without needing to keep its place in the argument list.

**Comment by vincentarelbundock** [comment]
Oh, I like this. Thanks for the suggestion! Will think about it.

**Comment by vincentarelbundock** [comment]
I implemented a first version of this. If you install the development version from Github, the following commands should work as expected:

```r
library(modelsummary)

mod <- lm(vs ~ drat + mpg, mtcars)

# hc standard errors
modelsummary(mod, statistic_override = "robust")
modelsummary(mod, statistic_override = "stata")
modelsummary(mod, statistic_override = "HC3")

# clustered standard errors
modelsummary(mod, statistic_override = ~cyl)
```

For some reason, I can't replicate the clustered standard errors from the `estimatr` package, but I manually checked them against `fixest` and `sandwich`, and the one-sided formula seems to work fine.

If you get a chance to try it, I'd appreciate any feedback you may have.

I'll open a new Issue to consider name change of `statistic_override` because that feels like a different question than the technical implementation of keywork shortcuts for "robust".

**Comment by vincentarelbundock** [comment]
I also changed the documentation a bit:

<img width="806" alt="Screen Shot 2020-12-16 at 22 38 22" src="https://user-images.githubusercontent.com/987057/102441015-6dfd9100-3fef-11eb-9958-0ccb786b85fc.png">

**Comment by NickCH-K** [comment]
Works for me! This is great. Notes:

1. You're not matching **estimatr** because it uses `vcovCL(type = 'HC2')`. 
2. Would it be possible to structure it to accept a list of strings/formula? A loop could convert each one into a function and then it would just be the same as sending a list of functions, one per column, as is currently possible. Adding a `'classical'` string option that doesn't adjust SEs would probably be a good idea if going this route.

**Comment by vincentarelbundock** [comment]
Cool.

1. I don't know of good theoretical reasons to prefer one type over another, so i just picked the `sandwich` default. Good for you?

2. Adding `classical` is a good idea. Will do.

You can already send a list, and it can even be a "mixed" list like this:

```r
library(modelsummary)

m = lm(hp ~ mpg + drat, mtcars)
m = list(m, m, m)
s = list("robust", ~cyl, vcov)
modelsummary(m, statistic_override=s)
```

**Comment by NickCH-K** [comment]
Oh! In that case, `statistic_override = list()` doesn't seem to currently work if it's all strings and has length > 1. Multiple clusters or mixed functions and a single string works. That's what I was trying it with which is why I didn't think it worked :P any other configuration seems fine.

```r
library(modelsummary)
m1 <- lm(hp~mpg+am, data = mtcars)

# Fine
msummary(list(m1,m1,m1), statistic_override = 'robust')
msummary(list(m1,m1,m1), statistic_override = c('robust',~cyl, sandwich::vcovHC))
msummary(list(m1,m1,m1), statistic_override = c('robust','robust', sandwich::vcovHC))

# Error:
msummary(list(m1,m1,m1), statistic_override = c('robust','robust','robust')
```

Specifically I get

```r
Error in extract_statistic_override(model, statistic_override = statistic_override,  : 
  Could not retrieve a valid variance-covariance matrix using the function supplied in `statistic_override`.
```

**Comment by grantmcdermott** [comment]
Just catching up on this thread now after seeing the PR ping. It's late and I'm on my phone, so very briefly:

- Strong vote for 'vcov'. It's the most consistent argument name to use.
- Yes, I'd stick with sandwich defaults.
- Speaking of which... I'm not sure about "classical". It's harder to pin down a consistent name for "standard" SEs across packages here and sandwich defaults if it's blank. In that spirit, I'd lean NULL or maybe "iid" (or both as accepted aliases).
