### ISSUE TITLE
`add_rows` that span columns in the middle of a table (not headers)

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#196]
This is probably impossible, since `modelsummary` works with different table engines, but I thought I would bring it up:  would there be a way to add model statistics that span several columns? This would be a great addition to the `add_rows` argument and be helpful, for instance, for model comparisons such as the below:

![image](https://user-images.githubusercontent.com/60155545/103357393-fa598a80-4aaa-11eb-9ff1-0d5569e0b664.png)

**Comment by vincentarelbundock** [comment]
Hmm yeah, probably very difficult and best done in "post-production". 

Out of curiosity, how did you do this one? What are the `gt` or `kableExtra` commands you used?

**Comment by LukasWallrich** [comment]
I actually don't think that `gt` supports merging cells (yet?), so that I ended up using `gt` to create the HTML-code and then added the additional rows with glued HTML code: https://github.com/LukasWallrich/rNuggets/blob/master/R/lm_tables.R ... not particularly elegant, and obviously a pain whenever I don't just need an HTML table ... based on some quick googling, `kableExtra`  also doesn't support merging columns (though it can merge rows), so that I am still looking for a better solution.

**Comment by vincentarelbundock** [comment]
Right, I couldn't find an easy way to do it with either packages, so I was wondering. Unfortunately, I'm afraid this means there won't be an easy way to do this with `modelsummary` either. In `kableExtra` you might be able to inject code using one of the functions. For example, I think that `row_spec` has `add_latex_after` or similar, but I'm not sure if there's an analogue for HTML.

From an infrastructure perspective, the problem is that `modelsummary` is purely data.frame (i.e., rectangular cells) based, and it outsources all the fancy stuff to external tablemaking packages. I truly believe this is what makes the strength of the package, but it also means that I'm dependent on upstream packages to implement functions to modify tables in more fundamental ways like this.

Sorry.

**Comment by LukasWallrich** [comment]
Thanks a lot for looking into it - that's what I expected, but I thought I would bring it up just in case.
