### ISSUE TITLE
Overwrite coefficient/standard errors with pre-processed "tidied" model summaries

### ISSUE THREAD

**Issue by svmiller** [vincentarelbundock/modelsummary#221]
This is admittedly convoluted but I've had to do something like this for two projects (one involving bootstrapped standard errors and another involving simulations from a uniform distribution for a covariate with low/high bounds). I know `{stargazer}` can do something like what I propose here and I'm curious if `{modelsummary}` can or if it would be worthwhile to add it as a feature if it could not.

Assume this kind of set up for illustration's sake. I have a model that flunks a B-P test for homoskedastic errors. I know `{modelsummary}` supports on-the-fly standard error corrections a la `{fixest}`, but I want to bootstrap those standard errors. The process looks similar to [what I did here](http://svmiller.com/blog/2020/03/bootstrap-standard-errors-in-r/).

First, I run the simple model (after loading relevant packages) and extract a tidied summary of the model output.

```
library(modelsummary)
library(modelr)
library(tidyverse)
library(stargazer)

# This will flunk a B-P test for homoskedastic errors.
# This is at least a partial justification for bootstrapping
summary(M1 <- lm(mpg ~ cyl, mtcars))

tidyM1 <- broom::tidy(M1)
```
I elect to bootstrap those standard errors, akin to this.

```
# Let's bootstrap this.

set.seed(8675309)
mtcars %>%
  bootstrap(100) %>%
  mutate(lm = map(strap, ~lm(mpg ~ cyl, 
                             data = .)),
         tidy = map(lm, broom::tidy)) %>%
  pull(tidy) %>%
  map2_df(.,
          seq(1,100),
          ~mutate(.x, resample = .y)) -> bootmods

bootmods %>%
  group_by(term) %>%
  summarize(mean_est = mean(estimate),
            sd_est = sd(estimate)) -> bootsums
```

I eye-ball what I've done to see that my standard errors get a bit more diffuse. Nothing major, but I expected that.

```
tidyM1
bootsums
```
Now, I know `{stargazer}` will do this. Basically, I have `{stargazer}` format what I think of as a "dummy model" where the DV and IV(s) match what I have. In this case, I'll just call `M1` twice. Importantly, though,`{stargazer}` allows me to manually supply the coefficients and standard errors based off pre-processed model summaries. This is the `coef=` and `se=` parameters in `stargazer()`.

```
stargazer(M1, M1,
          # for readability, let's do "text"
          type='text',
          column.labels = c("OLS", "Bootstrapped SEs"),
          # Omit model statistics by default.
          # You can supply your own. See:
          # http://svmiller.com/blog/2020/05/better-way-to-include-random-effects-stargazer/
          omit.table.layout = "s",
          dep.var.labels = "DV: Miles per Gallon in 1970-something for whatever reason",
          # This is what I really want to do, though...
          coef = list(tidyM1$estimate, tidyM1$estimate),
          se = list(tidyM1$std.error, bootsums$sd_est))
```
Can `{modelsummary}` do something like this? I saw from the documentation that you can write your own custom extractor functions for models without the most straightforward support. However, in my case, I've already effectively done that. I just want to see if `{modelsummary}` will allow me to use those pre-processed model summaries to overwrite things supplied by a "dummy model."

Any input appreciated. I might have missed something here.

**Comment by vincentarelbundock** [comment]
Hey!

I’m out of town reading this on a phone, so not sure I 100% get what you mean. But it sounds kind you just want to supply a list of vectors.

In principle, you should be able to supply a list of vectors to the `vcov` argument and it should Just Work. 

I don’t think there’s something that easy for estimates though. In that case, I would probably define a `tidy_custom.lm` method that takes an `lm` model, does the bootstrap, and returns a dataframe with three columns: term, estimate, std.error.

See the example where I swap out estimates in the “Customizing models” section here: 

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html

Then, you won’t have to repeat your bootstrap code and everything should just work.

The most manual approach would be to create a list with two element a called `tidy` and `glance` and to assign the `modelsummary_list` class to that object.

let me know if any of those options work for you. If they don’t let me know what the problem is and I’ll take a closer look next week.

**Comment by svmiller** [comment]
The `vcov` route won't seem to work for what I may want. I see you can supply your own vectors, a la this:

```
library(modelsummary)
data(trees)
models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees)

modelsummary(models, 
  vcov = list(c("(Intercept)"="", "Height"="!"),
                            c("(Intercept)"="", "Height"="!", "Volume"="!!")))
```

However, that would be manually entering standard errors for every parameter in the model---which is great for forcing them to match but less ideal for automation. Also, if I wanted to trick `modelsummary` that the supplied standard errors would make a parameter discernible (or not discernible) from zero, this route won't seem work. Here, I'm mimicking a situation where the bootstrapping process effectively "reversed" all the results (in terms of statistical significance).

```
modelsummary(models, 
             vcov = list(c("(Intercept)"=.1, "Height"=4),
                         c("(Intercept)"=10, "Height"=.01, "Volume"=20)), stars=TRUE)
```

I'm going to give the `modelsummary_list` you mentioned a stronger look and report back.  Following [this link and reprex](https://github.com/vincentarelbundock/modelsummary/issues/143), I think I'm wanting something similar.

I feel bad for taking up your time out of town. Enjoy it! Promise me you're still in Quebec even as you're out of town; it's my favorite/the best part of Canada.

**Comment by svmiller** [comment]
Just following up that this 1) seems to do it and 2) will seem to do it when generalized outward for more complex models. I also offer it as a potential addition to [the tutorial for this package](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html) if you'd like to explain `modelsummary_list` more. I didn't quite see it in the tutorial, only how you might extract information from models not yet supported by `broom`.

```
library(modelsummary)
library(modelr)
library(tidyverse)

# This will flunk a B-P test for homoskedastic errors.
# This is at least a partial justification for bootstrapping
summary(M1 <- lm(mpg ~ cyl, mtcars))

tidyM1 <- broom::tidy(M1)

# Let's bootstrap this.

set.seed(8675309)
mtcars %>%
  bootstrap(100) %>%
  mutate(lm = map(strap, ~lm(mpg ~ cyl, 
                             data = .)),
         tidy = map(lm, broom::tidy)) %>%
  pull(tidy) %>%
  map2_df(.,
          seq(1,100),
          ~mutate(.x, resample = .y)) -> bootmods

bootmods %>%
  group_by(term) %>%
  summarize(mean_est = mean(estimate),
            # I know, I know... but tidy stuff wants `std.error` here...
            `std.error` = sd(estimate)) %>%
  rename(estimate = mean_est) %>%
  # note: I'm squeamish about doing this manually for t stuff, but modelsummary wants p-values
  # We have 30 DFs too. I always worry I'm going to screw up how lm() naturally does this.
  mutate(statistic = estimate/`std.error`,
         `p.value` = 2 * pt(abs(statistic), 30, lower.tail = FALSE)) -> bootsums


# Let's eye-ball what might be different here...
tidyM1
bootsums

list(
  tidy = tidyM1,
  glance = data.frame(test = "ABC")
) -> listM1

class(listM1) <- "modelsummary_list"


list(
  tidy = bootsums,
  glance = data.frame(test = "DEF")
) -> listboot

class(listboot) <- "modelsummary_list"

# Voila! Thanks, Vincent!
modelsummary(list(listM1, listboot), stars=TRUE)
```

**Comment by vincentarelbundock** [comment]
Nice!

let’s leave this issue open for now. I actually think this is a perfect use case for `tidy_custom.lm` so I might fold this into a case study. That mechanism is a bit harder to wrap one’s head around, but it’s super powerful.

Did you find a `modelsummary_list` example anywhere? If not, there should definitely be one!

PS: yeah, we’re only about 1hr away from home. It’s quiet and there’s lots of beautiful snow!

**Comment by vincentarelbundock** [comment]
@svmiller , so here's what I had in mind. You create one function that can bootstrap any `lm` model, and every time you call `modelsummary`, it will automatically bootstrap the whole thing for you and update the standard errors.

My example is more minimalist than yours (doesn't do stars, for ex.), but hopefully it illustrates the general strategy well enough.

```r
library("modelsummary")
library("broom")
library("tidyverse")
library("modelr")

tidy_custom.lm <- function(x, ...) {
  model.frame(x) %>%
    modelr::bootstrap(n = 500) %>%
    mutate(results = map(strap, ~ update(x, data = .)),
           results = map(results, tidy)) %>%
    unnest(results) %>%
    group_by(term) %>%
    summarize(std.error = sd(estimate),
              estimate = mean(estimate))
}

mod = list(
  lm(hp ~ mpg, mtcars) ,
  lm(hp ~ mpg + drat, mtcars))

modelsummary(mod)
```

**Comment by vincentarelbundock** [comment]
I added an annotated version of this code to the "Case Studies" section of the docs: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#case-studies-1

**Comment by svmiller** [comment]
I like this approach a lot. It's going to be more widely applicable for when you want to bootstrap standard errors by default (i.e. the equivalent of ", robust" for those of us coming of age with Stata 15 years ago). In my particular application, I was wanting to compare the classical standard errors with bootstrapped standard errors and was worried that `tidy_custom.lm` would overwrite my ability to get information from a default linear model. `modelsummary_list` works a bit better for me for this application, but your case study with `tidy_custom.lm` is also really nice and extendable.

Thanks again for all of this. I learned a lot more about the package (which is a godsend for having to dance between PDF and Word docs for workflow).

**Comment by vincentarelbundock** [comment]
Oh yes, that's right. `modelsummary_list` is a totally workable strategy. Two minor things to consider:

1. We can assign `tidy_custom.whatever` instead and assign a new `whatever` class to just the models we want to bootstrap.
2. The extra tricky part with my recommendation is that we need to remember to `rm` the method, otherwise, like you point out, every model of the class will be bootstrapped.

Just to illustrate the class assignment thing I just suggested, here I assign a new `boot` class to the model I want to bootstrap, and renamed the method `tidy_custom.boot`:

``` r
library("modelsummary")
library("broom")
library("tidyverse")
library("modelr")

tidy_custom.boot <- function(x, ...) {
  model.frame(x) %>%
    modelr::bootstrap(n = 500) %>%
    mutate(results = map(strap, ~ update(x, data = .)),
           results = map(results, tidy)) %>%
    unnest(results) %>%
    group_by(term) %>%
    summarize(std.error = sd(estimate),
              estimate = mean(estimate))
}

mod = list()
mod$Classical = lm(hp ~ mpg, mtcars)
mod$Bootstrap = lm(hp ~ mpg, mtcars)
class(mod$Bootstrap) = c("boot", "lm")

modelsummary(mod, output = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Classical</th>
<th style="text-align: center;">Bootstrap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">328.618</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(27.433)</td>
<td style="text-align: center;">(31.539)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpg</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-9.085</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.310)</td>
<td style="text-align: center;">(1.440)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.602</td>
<td style="text-align: center;">0.602</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.589</td>
<td style="text-align: center;">0.589</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">336.9</td>
<td style="text-align: center;">336.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">341.3</td>
<td style="text-align: center;">341.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-165.428</td>
<td style="text-align: center;">-165.428</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">45.460</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

``` r
rm("tidy_custom.boot")
```

<sup>Created on 2021-03-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by svmiller** [comment]
```
class(mod$Bootstrap) = c("boot", "lm")
```

I'm so allergic to the idea of overwriting classes that I forgot I could just add to it if I still wanted to retain the `summary()` function. Man, I'm dumb. :P 

(i.e. this is all really good stuff)

**Comment by vincentarelbundock** [comment]
Great, sounds like we can close this. For references I added an example with `modelsummary_list`:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i-

And a "cast study" with `tidy_custom`:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#bootstrap-1

**Comment by svmiller** [comment]
I believe so. I think we can close this. Thanks again for everything.
