### ISSUE TITLE
Extending the SVG plots to `datasummary`

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/modelsummary#250]
The histograms produced by `datasummary_skim` are extraordinary! It would be wonderful if `datasummary` can adopt such a function to do so, even only when `kableExtra` is TRUE. Meanwhile, as mentioned in #151, the unicode version is still great for Word tables, though. Sorry for being picky😏

**Comment by vincentarelbundock** [comment]
Thanks for the feedback, I really appreciate it!

I'm not sure I understand your feature request. Are you asking for a way to inlclude the same SVG/kableExtra histograms in a `datasummary` (and *not* in a `datasummary_skim`)? 

If so, this is unfortunately not something I will implement. In `datasummary`, all of the interpretation of the formula is delegated to the `tables` package, so there is no way to represent additional information outside of that mechanism. In `datasummary_skim`, I can add a new column because I know exactly what to expect: 1 variable per row, and I know which variable is on each row. This is not the case for `datasummary`, which can have nested variables as rows.

Any solution to this would necessarily be (a) complicated, (b) fragile, (c) hackish, and (d) a lot of work to implement. Sorry!

**Comment by sammo3182** [comment]
Thank you for the prompt reply, Vincent. In this case, is there a way to customize the `datasummary_skim` a little bit, for instance, not showing the unique value, the missing ratio, or the median?

**Comment by vincentarelbundock** [comment]
Not at the moment, but I'll definitely think about that idea. I'm a bit hesitant because I conceived of `datasummary_skim` as an opinionated first cut, and provide a general mechanism for customization in the form of `datasummary`, which can be used in combination with `spec_hist` to manually add histograms. But maybe omitting certain columns is simple enough that I can be flexible on this point. Will think about it seriously.

In the meantime, it's very easy for you to manually add an extra column with the histograms. All you have to do is create a list with each of your variables as distinct elements, and then call the `kableExtra::spec_hist` function. The [`kableExtra` document](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#HTML_Only_Features) is pretty clear on how to do this, and you may want to refer to the `datasummary_skim` code to see exactly how I combine `datasummary` and `spec_hist` together to produce the output you see when calling `datasummary_skim`:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/datasummary_skim.R#L222

I hope you'll see that it's quite simple to combine a custom `datasummary` call with the `kableExtra::spec_hist`.

**Comment by sammo3182** [comment]
Ha, thank you for the explanation. I understand the concern---every function has its unique goal, otherwise, they shouldn't be a separate function but an argument of a combo. The reason of the above request is just about the beautiful and precise histogram but `datasummary` doesn't.  I'll definitely check out the trick! In the meantime, it would be wonderful if you could consider the request to customize `datasummary_skim` just a tiny bit😋Thanks again for the amazing package! I've already asked my students to totally switch to `modelsummary` from `stargazer`, hey-hey~

**Comment by vincentarelbundock** [comment]
ping Alexander Wuttke if/when done

**Comment by vincentarelbundock** [comment]
Thanks again for your thoughtful suggestions.

Unfortunately, for the reasons stated above, it is not possible to add SVG histograms directly to `datasummary`. However, it is *very* easy to add them manually after the datasummary table is computed. I have now added an example to the vignette:

https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#histograms-1

I have tried to allow customization of `datasummary_skim` and, for very boring reasons, it is not easy to do "cleanly". Since I show above that it is easy to histograms manually, I hope that my vignette examples will be enough.

I will now close this issue, but feel free to open others if you have other ideas and suggestions. I love to get them!
