### ISSUE TITLE
Give the possibility to remove "Cluster vars" and "FE" rows

### ISSUE THREAD

**Issue by phl43** [vincentarelbundock/modelsummary#254]
I'm using ```modelsummary``` with ```lfe``` to summarize the results of models with fixed effects and clustered standard errors, but I'd like to remove the row that indicates the variable used to cluster standard errors and the rows that indicate whether a given fixed effect was included in a model from the table produced by ```msummary``` and I can't find a way to do that anywhere in the documentation. Is there a way to do that and, if not, do you think you could add the option to do so?

**Comment by vincentarelbundock** [comment]
Thanks for filing an issue. Could you please provide a minimal reproducible example, maybe using one of the R built in datasets or something easy to download?

**Comment by phl43** [comment]
Sure, sorry for not doing so right away, here is a reproducible example:
```
set.seed(42)
n <- 1e3
d <- data.frame(
  # Covariates
  x1 = rnorm(n),
  x2 = rnorm(n),
  # Individuals and firms
  id = factor(sample(20, n, replace=TRUE)),
  firm = factor(sample(13, n, replace=TRUE)),
  # Noise
  u = rnorm(n) )
# Effects for individuals and firms
id.eff <- rnorm(nlevels(d$id))
firm.eff <- rnorm(nlevels(d$firm))
# Left hand side
d$y <- d$x1 + 0.5*d$x2 + id.eff[d$id] + firm.eff[d$firm] + d$u
## Estimate the model and print the results
est <- felm(y ~ x1 + x2 | id + firm | 0 | id, data = d)

msummary(
  est,
  output = "gt"
)
```

This produces the following output:
<img width="204" alt="Capture d’écran 2021-04-07 à 01 20 16" src="https://user-images.githubusercontent.com/36411538/113789482-78c76780-973f-11eb-8134-6c7d5b61bfd3.png">
I would like to get rid of the following rows: "Cluster vars", "FE: firm" and "FE: id".

**Comment by vincentarelbundock** [comment]
Great, thanks!

Two things:

1. Turns out I deprecated the FE information helpers from `lfe`. A little while ago, but the package was pulled from CRAN because it is no longer maintained. Some community members helped put it back there, but the people who did that now recommend using `fixest` instead of `lfe` (it's also faster and more flexible). Since I deprecated the helpers, you can install the Github version of `modelsummary` and you should not see the FE information: `remotes::install_github("vincentarelbundock/modelsummary")`  (Make sure you start a fresh session of R after install.
2. You can always omit information from the bottom of the table using the `gof_omit` argument, which accepts regular expressions like "FE|R2", which would omit R squareds and FE rows.

Hope that helps. Let me know if it doesn't.

**Comment by phl43** [comment]
Thanks, ```gof_omit``` with a regular expression works great, but I'll also look into ```fixest``` because I just checked it out and it looks cool.
