### ISSUE TITLE
What to do inside or outside?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#26]
Should we have arguments for:

* notes
* footnotes
* column spans
* row groups
* title subtitle

when those are available in `gt`? My intuition is it's fine to have redundancy for convenience, but I'm not sure where to stop.

**Comment by sammo3182** [comment]
Thank you again for the amazing pacakage and all the efforts of making it increasingly more convenient and awesome!

Aye on keeping the arguments in the function. A suggestion for the PDF output, though: right now if the content is in double-space, so do the notes for `gtsummary` tables. Is there a way to allow local single-space to make those notes more like notes rather than paragraphs after the table? `texreg` can do that by manually writing the notes in the latex environment, e.g., `"\\parbox{\\linewidth}{\\vspace{2pt} The notes.}"`.  On the other hand, `gtsummary` does a way better job on the table outline when multiple models are involved. So, I will definitely stick with `gtsummary`, while hoping it could be even more flexible for cutsomization. 

By the way, could I ask two quick questions here? I don't think neither is worth openning an issue to ask:

1. Is there a way to shrink the table fonts or control for the table width when so many models are involved? (Something like adding `\footnotesize` or `\scriptsize`?)
1. Your fix of the title bug + label function (https://github.com/rstudio/gt/pull/143) is still not merged to the `gt` package, right? Is there a way to get it? I'm quite annoying by including a subtitle everytime when I need a title...

**Comment by vincentarelbundock** [comment]
This sounds like an interesting use-case, but I'm not sure it warrants including a whole new argument in the function. The best way to deal with this would probably to include some LaTeX commands in `gt`'s `tab_source_note` function. 

This is already possible with HTML and markdown:

```
library(gt)
gtsummary(models) %>%
    tab_source_note(html('<em>Blah blah</em>'))

gtsummary(models) %>%
    tab_source_note(md('*Blah blah*'))
```

Unfortuntately, if you try the same thing with LaTeX code, it'll be escaped, so you'll see lots of `\textbackslash` instead of your actual command. The solution is probably to implement a new function (`gt::latex`?) like `gt::md` or `gt::html`.

Feel free to make that suggestion on `gt`'s github.

Font size is possible, but only in html so far. I have added information to the README (also see this issue which may be relevant: https://github.com/rstudio/gt/issues/176). This is another thing that will improve when the latex output functionality of `gt` gets some love.

You are right that that PR has not been merged yet. You can certainly install the branch in question if you want. It should work. There are many tutorials on how to install branches with git.

**Comment by sammo3182** [comment]
Thank you for the prompt reply! The PR works pretty well. For those who don't know how to install this update: 

```r
devtools::install_github("rstudio/gt#143")
```

I also posed a suggestion for `gt::latex` at the `gt` repo (https://github.com/rstudio/gt/issues/178). Hope they could make an effort on that one day.
