### ISSUE TITLE
Support new statistical models

### ISSUE THREAD

**Issue by cccneto** [vincentarelbundock/modelsummary#267]
`modelsummary` doesn't work for the Bivariate Probit Model, GJRM Package. Maybe it is possible to add this model into modelsummary. What do you think?

Below is the data for a simulation.

```
library(GJRM)

dat <- data.frame(
    x1 = rnorm(40, 1:10),
    x2 = rnorm(40, 1:30),
    bid1 = sample(1:5, 40, replace = TRUE),
    bid2 = sample(1:5, 40, replace = TRUE),
    y1 = sample(0:1, 40, replace = TRUE),
    y2 = sample(0:1, 40, replace = TRUE))

f.list <- list(
  y1 ~ bid1 + x1 + x2,
  y2 ~ bid2 + x1 + x2)

mr <- c("probit", "probit")

mod <- gjrm(f.list, dat, Model="B", margins= mr)

summary(mod)
```

**Comment by vincentarelbundock** [comment]
Thanks for the feature request, I really appreciate it!

`modelsummary` does not extract estimates or statistical results from model objects itself. Instead, it relies on [the `broom`](https://broom.tidymodels.org/) and the [`parameters`](https://github.com/easystats/parameters) packages to do this work.

The `broom` package uses two simple functions to extract model info: `tidy` and `glance`. In an ideal world, the package maintainers for individual statistical models would supply these functions for their models. Many maintainers are already doing this, as `tidy` and `glance` look like an emerging "standard" in the community.

If the package maintainer is unwilling or unable to implement these functions, the next best option is to file requests on the Github pages of the `broom` and/or `parameters` packages to request support for the model in question. Obviously, the maintainers of `broom` and `parameters` packages are doing this for free, and their time is limited, so it's always a great idea to supply code if possible.

Finally, if you just want `modelsummary` to work immediately with your (previously unsupported) model, it is *very* easy to define `tidy` and `glance` methods that will do the work for you. This section of the documentation gives the intuition and a couple very simple examples:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i-

In your case, things are a tiny bit more complicated because the `SemiParBIV` objects produced by the `GJRM` package are multi-equation models. But it's still really not that hard! 6 steps:

1. Use the `summary` function to extract estimates. 
2. Notice that the results of each equation is stored in data.frames called `tableP#`.
3. Loop over equation results and rename columns following `broom` convention: `estimate`, `std.error`, `statistic`, `p.value`
4. Add a new column with the equation number
5. Combine the estimates from different equations
6. Define a `glance` method that extracts the number of observations and some other info

After defining those functions, `modelsummary` should work with any model of this class you feed it (hopefully).

```r
library(modelsummary)
library(broom)
library(dplyr)
library(GJRM)

# Simulate data and estimate model
dat <- data.frame(
    x1 = rnorm(40, 1:10),
    x2 = rnorm(40, 1:30),
    bid1 = sample(1:5, 40, replace = TRUE),
    bid2 = sample(1:5, 40, replace = TRUE),
    y1 = sample(0:1, 40, replace = TRUE),
    y2 = sample(0:1, 40, replace = TRUE))

f.list <- list(
  y1 ~ bid1 + x1 + x2,
  y2 ~ bid2 + x1 + x2)

mr <- c("probit", "probit")

mod <- gjrm(f.list, dat, Model="B", margins= mr)

# Custom extractor functions
tidy.SemiParBIV <- function(x, conf.level = 0.95, ...) {
    s <- summary(x, prob.lev = 1 - conf.level, ...)
    s <- s[grepl("tableP", names(s))]
    s <- s[sapply(s, is.null) == FALSE]
    for (i in seq_along(s)) {
        colnames(s[[i]]) <- c("estimate", "std.error", "statistic", "p.value")
        s[[i]] <- data.frame(s[[i]])
        s[[i]]$equation <- paste("Equation", i)
        s[[i]]$term <- row.names(s[[i]])
    }
    out <- bind_rows(s)
    out
}

glance.SemiParBIV <- function(x, ...) {
  out <- data.frame(
    nobs = x$n,
    robust = x$robust)
  out
}

modelsummary(mod, output = "markdown", group = equation + term ~ model)
```

|           |            | Model 1 |
|:----------|:-----------|:-------:|
|Equation 1 |(Intercept) | -0.873  |
|           |            | (0.752) |
|           |bid1        |  0.210  |
|           |            | (0.151) |
|           |x1          |  0.062  |
|           |            | (0.074) |
|           |x2          | -0.024  |
|           |            | (0.024) |
|Equation 2 |(Intercept) |  0.277  |
|           |            | (0.669) |
|           |x1          |  0.006  |
|           |            | (0.070) |
|           |x2          | -0.026  |
|           |            | (0.023) |
|           |bid2        |  0.028  |
|           |            | (0.138) |
|           |Num.Obs.    |   40    |
|           |robust      |  FALSE  |

**Comment by strengejacke** [comment]
``` r
library(GJRM)
#> Loading required package: mgcv
#> Loading required package: nlme
#> This is mgcv 1.8-34. For overview type 'help("mgcv-package")'.
#> 
#> This is GJRM 0.2-4.
#> For overview type 'help("GJRM-package")'.
library(parameters)

dat <- data.frame(
  x1 = rnorm(40, 1:10),
  x2 = rnorm(40, 1:30),
  bid1 = sample(1:5, 40, replace = TRUE),
  bid2 = sample(1:5, 40, replace = TRUE),
  y1 = sample(0:1, 40, replace = TRUE),
  y2 = sample(0:1, 40, replace = TRUE))

f.list <- list(
  y1 ~ bid1 + x1 + x2,
  y2 ~ bid2 + x1 + x2)

mr <- c("probit", "probit")

mod <- gjrm(f.list, dat, Model="B", margins= mr)

model_parameters(mod)
#> # Equation1
#> 
#> Parameter   | Coefficient |   SE |        95% CI |     z |     p
#> ----------------------------------------------------------------
#> (Intercept) |       -1.32 | 0.71 | [-2.72, 0.08] | -1.85 | 0.064
#> bid1        |        0.30 | 0.15 | [ 0.01, 0.60] |  2.02 | 0.043
#> x1          |   -9.92e-04 | 0.07 | [-0.14, 0.14] | -0.01 | 0.989
#> x2          |        0.02 | 0.03 | [-0.03, 0.08] |  0.82 | 0.412
#> 
#> # Equation2
#> 
#> Parameter   | Coefficient |   SE |        95% CI |     z |     p
#> ----------------------------------------------------------------
#> (Intercept) |        0.52 | 0.58 | [-0.61, 1.64] |  0.90 | 0.370
#> bid2        |       -0.16 | 0.14 | [-0.42, 0.11] | -1.16 | 0.245
#> x1          |        0.02 | 0.07 | [-0.12, 0.16] |  0.26 | 0.792
#> x2          |       -0.02 | 0.02 | [-0.07, 0.03] | -0.70 | 0.481
```

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
To translate a bit for @cccneto , what this means is that @strengejacke was generous enough to add support for this model type in `modelsummary`'s upstream packages (`easystats`). If you install the development version of `insight` and `parameters`, your model should work immediately in `modelsummary`:

First install the latest versions:

```r
library(remotes)
install_github("easystats/insight")
install_github("easystats/parameters")
```

Then, restart `R` completely for the changes to take effect.

Finally, estimate and summarize your model:

```r
library(GJRM)
library(modelsummary)

dat <- data.frame(
  x1 = rnorm(40, 1:10),
  x2 = rnorm(40, 1:30),
  bid1 = sample(1:5, 40, replace = TRUE),
  bid2 = sample(1:5, 40, replace = TRUE),
  y1 = sample(0:1, 40, replace = TRUE),
  y2 = sample(0:1, 40, replace = TRUE))

f.list <- list(
  y1 ~ bid1 + x1 + x2,
  y2 ~ bid2 + x1 + x2)

mr <- c("probit", "probit")

mod <- gjrm(f.list, dat, Model="B", margins= mr)

modelsummary(mod, group = component + term ~ model)
```

Thanks @strengejacke !

**Comment by strengejacke** [comment]
nice to see that modelsummary will immediately support new models once these are supported by the parameters/performance packages. 👍

**Comment by cccneto** [comment]
Hey Guys, thank you so much! I received a lot of help from both of you, and it was constructive. I have done my table following your instructions. It's worked!
