### ISSUE TITLE
Number of non-missing obs is incorrect in `datasummary`

### ISSUE THREAD

**Issue by julianlanger** [vincentarelbundock/modelsummary#270]
I am currently trying to summarize a dataset that has missing obs for some variables. However, when I use `datasummary` with `N`, this gives me simply the number of rows in the dataset for all variables. I don't  think `NUnique` is the correct statistic either, since it is not about the number of unique obs but the number of non-missing ones. 

```
library(dplyr)
library(modelsummary)
  
test <- tribble(
    ~a, ~b,
    1, 2, 
    1, 2,
    3, NA_integer_
  )

datasummary(data = test, a + b ~ N + NUnique)
```

**Comment by julianlanger** [comment]
OK, I can create my own function: 

`n_nm <- function(x) as.character(sum(!is.na(x)))`.

However, I find the `N` a bit misleading then and not very informative.

**Comment by vincentarelbundock** [comment]
Thanks for raising this issue @julianlanger !

FYI, the use-case I had in mind when I created the `N` function was this:

``` r
library(modelsummary)
library(palmerpenguins)

datasummary(
  species ~ N + flipper_length_mm * Mean,
  data = penguins,
  output = "markdown")
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">189.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">195.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">217.19</td>
</tr>
</tbody>
</table>

So I wouldn't say it is "only informative in the stacked case". But I agree that the situation is confusing, since we have two possible meanings for a single letter: (1) the number of rows in a subset/factor, and (2) the number of non-missing values for a variable. Both sound like "legitimate" uses of the letter "N" to me.

Unfortunately, for obscure reasons having to do with the [`tables` package](https://cran.r-project.org/web/packages/tables/index.html) -- which `modelsummary` uses under the hood -- it seems quite difficult to have a single function `N` that can handle the two use-cases / meanings. I will think about a bit more, but I can't promise a better solution than the custom function you already found.



Note to self: the problem is that if we define:

```r
N <- function(x) sum(!is.na(x))
```

and if we then call:

```r
datasummary(species ~ N, penguins)
```

then `tables` will feed a logical vector that indicates subsets of species to `N`, and `N` will return 0 since there are no missing values in that index.

**Comment by vincentarelbundock** [comment]
And all I needed to find a solution was apparently to write down the problem in words.

If you install the new version from Github, you should be able to do this:

``` r
library(modelsummary)
library(palmerpenguins)
library(tibble)

test <- tribble(
    ~a, ~b,
    1, 2, 
    1, 2,
    3, NA_integer_
  )

datasummary(
  species ~ N + flipper_length_mm * Mean,
  output = "markdown",
  data = penguins)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">189.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">195.82</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">217.19</td>
</tr>
</tbody>
</table>

``` r
datasummary(
  a + b ~ N + NUnique,
  output = "markdown",
  data = test)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">NUnique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">a</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">b</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>

**Comment by julianlanger** [comment]
Cool, thank you! Nice that both things works now.
