### ISSUE TITLE
Unsuccessful standard error adjustments

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#278]
Hi Vincent, I'll open a few more issues--apologies in advance. I also promise to work on the other two outstanding ones later today! :)

This one is more of a suggestion. In the case below, where the custom standard error adjustment wasn't successful, wouldn't it (a) be worth raising the warning to an error, and (b) wouldn't it be better to not add the row `Std. Errors: C: cyl`? I would be especially in favor of fixing (b), but I do think erroring would also be appropriate given that the standard errors shown in the table are way off. When there is an error, one also wouldn't have to fix (b).

``` r
library("modelsummary")
library("plm")
mod <- plm(mpg ~ disp, index = "cyl", data = mtcars)
modelsummary(mod, vcov = ~cyl, output = "markdown")
#> Warning in get_vcov(model, vcov = vcov, conf_level = conf_level, ...): Unable
#> to extract a clustered variance-covariance matrix from model of class plm. The
#> uncertainty estimates are unadjusted.
```

|             | Model 1 |
|:------------|:-------:|
| disp        | -0.027  |
|             | (0.011) |
| Num.Obs.    |   32    |
| R2          |  0.191  |
| R2 Adj.     |  0.105  |
| Std. Errors | C: cyl  |

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Issues are great! Keep 'em coming!

On (b), I totally agree. We should not display standard errors if `modelsummary` was unsuccesful at using `vcov`. I just looked at the code, and because of code separation issues it's tiny bit tricky to fix, but I'll look for a solution soon.

On (a), the reason why I only raise a warning is convenience. Internally, we use `lmtest::coeftest` to extract the vcov, but this package only support a tiny fraction of model types. When users pass `vcov="robust"`, but the model list includes both supported and unsupported, I thought it would be better to still produce a table with a warning.

I see the benefits of being more explicit, so I'm open to being convinced that a warning is insufficient. But I also think that people *should* look at warnings in general.

**Comment by elbersb** [comment]
> Issues are great! Keep 'em coming!
Noted! 

> I see the benefits of being more explicit, so I'm open to being convinced that a warning is insufficient. But I also think that people _should_ look at warnings in general.

Agreed, of course, that people should look at warnings. But the more I think about it, the more I think that an error is more appropriate, for three reasons: First, the user _explicitly_ requested different standard errors, otherwise they wouldn't have used `vcov = ...`. Second, the standard errors are such a critical part of the output. And third, this might circumvent other problems in the package, for instance, (a) wouldn't need fixing, and this would open a more general path to dealing with model classes where the SE adjustments are not successful (for instance, this might also be a way to deal with unsuccessful `fixest` adjustments).

**Comment by vincentarelbundock** [comment]
I'm convinced.

Let's make sure the error is super well-formatted and informative, though. Maybe it should even include some code examples.

**Comment by elbersb** [comment]
I can make a PR later today if you like
