### ISSUE TITLE
glance_custom only works if set in globalenv

### ISSUE THREAD

**Issue by adamaltmejd** [vincentarelbundock/modelsummary#319]
Building on previous issue with glance_custom and fixest: https://github.com/vincentarelbundock/modelsummary/issues/312, `modelsummary()` seems to only look for `glance_custom` methods in globalenv:

```
library(fixest)
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/plm/EmplUK.csv'
dat <- read.csv(url)
mod <- list()
mod[[1]] <- feols(emp ~ wage, dat)
mod[[2]] <- feols(emp ~ wage | firm, dat)
mod[[3]] <- feols(emp ~ wage | firm + year, dat)


glance_custom.fixest <- function(x) {
    out <- tibble::tibble(.rows = 1)
    for (n in x$fixef_vars) {
        out[[paste('OUT FUNCTION: ', n)]] <- 'Y'
    }
    return(out)
}

my_table <- function(x) {
    glance_custom.fixest <- function(x) {
        out <- tibble::tibble(.rows = 1)
        for (n in x$fixef_vars) {
            out[[paste('IN FUNCTION: ', n)]] <- 'Y'
        }
        return(out)
    }
    modelsummary(x)
}

my_table(mod)
```

Produces a table with "OUT FUNCTION" rather than "IN FUNCTION". If I wouldn't have supplied the global glance_custom no custom statistics would have been added at all. Is this by design? How do you recommend i add custom stats in functions?

**Comment by vincentarelbundock** [comment]
I'm not sure that "by design" really captures the (low) level of intentionnality behind this choice, but it certainly feels like the simplest approach. See here for how I defined the method and use it internally:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/glance_custom.R
https://github.com/vincentarelbundock/modelsummary/blob/main/R/get_gof.R#L73

In your case, it seems easy enough to assign the method to the global environment by assigning `glance_custom.fixest` with the double arrow operator `<<-` inside your function (and clean up the global environment after if you need to).

Can you foresee cases where this would be very problematic? Is there an easy implementation that would circumvent the problem?

**Comment by adamaltmejd** [comment]
Interesting, thanks for the quick reply. From a quick glance I'm not even sure why this isn't working from within the function's env? For my current use case I can just assign the method in the global env. You are probably right that the use case where it really needs to be assigned only locally is extremely fringe :).
