### ISSUE TITLE
dinm argument not working new version

### ISSUE THREAD

**Issue by kmarray98** [vincentarelbundock/modelsummary#374]
Hi

Myself and another grad student ran the same code and got different outputs today. I downloaded modelsummary 0.9.1 today, he has modelsummary 0.8.1. We both tried to run the following script

modelsummary::datasummary_balance(~ searchperiod,
data = dataset %>%
select(c(1,4:23)) %>%
mutate(searchperiod = if_else(
searchperiod == 1,
"With Search",
"Without Search")),
output = "latex",
fmt = "%.3f",
dinm = TRUE,
dinm_statistic = "p.value"
)
where `dataset' is just a dataframe (also does not work with a tibble). In his case, it gives the difference and p-value columns in the output table as it is supposed to. On my machine, it does not!

Best

Kieran

**Comment by vincentarelbundock** [comment]
"Does not work" is much too vague of a description for me to diagnose.

Please supply the complete error message, as well as a MINIMAL and REPRODUCIBLE example. See here for tips on how to do that:

https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

**Comment by kmarray98** [comment]
It does not output the column containing the differences, or the corresponding p_values, at all. It does not throw any error message.

Example

# lets make a small dataframe
vec1 <- c(1,1)
vec2 <- c(0,0)
vec3 <- c(1,0)
df <- as.data.frame(cbind(vec1, vec2, vec3))
colnames(df) <- c("foo", "foo2", "searchperiod")

# issue is that  `dinm=TRUE` returns the same table as `dinm=FALSE`

datasummary_balance(~ searchperiod,
data = df %>%
mutate(searchperiod = if_else(
searchperiod == 1,
"With Search",
"Without Search")),
dinm = TRUE
)

**Comment by vincentarelbundock** [comment]
Your example is not reproducible, because the data is not large (and complete) enough to calculate a difference in means. Notice the error here:

``` r
library(dplyr)
library(modelsummary)

df <- data.frame(foo = 1:1,
                 foo2 = c(0, 0),
                 searchperiod = c(1, 0)) %>%
    mutate(searchperiod = if_else(searchperiod == 1, "With Search", "Without Search"))

datasummary_balance(~ searchperiod, dat, dinm = TRUE)
#> Error in difference_in_means_internal(condition1 = condition1, condition2 = condition2, : If design is not pair-matched, every block must have at least two treated and control units.
```

However, extending it a little works on my computer:

``` r
df <- data.frame(foo = sample(0:1, 50, replace = TRUE),
                 foo2 = sample(0:1, 50, replace = TRUE),
                 searchperiod = sample(c("With Search", "Without Search"), 50, replace = TRUE))

datasummary_balance(~ searchperiod, data = df, dinm = TRUE, output = "markdown")
```

|      | With Search (N=23) Mean | With Search (N=23) Std. Dev. | Without Search (N=27) Mean | Without Search (N=27) Std. Dev. | Diff. in Means | Std. Error |
| :--- | ----------------------: | ---------------------------: | -------------------------: | ------------------------------: | -------------: | ---------: |
| foo  |                     0.4 |                          0.5 |                        0.7 |                             0.5 |            0.3 |        0.1 |
| foo2 |                     0.6 |                          0.5 |                        0.6 |                             0.5 |          \-0.1 |        0.1 |

A few questions:

  - Did you restart `R` completely after installing the new version? Are you sure you are *running* the latest `modelsummary`, and haven’t merely *installed* it?
  - Do other functions like `datasummary_skim` or `modelsummary` produce tables?
  - What happens if you change the function’s argument to `output="markdown"` or `output="gt"`?

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by kmarray98** [comment]
This example fails on my machine, in exactly the same way as above (after restarting R completely to doublecheck this)

**Comment by vincentarelbundock** [comment]
Weird. I ran the example on 3 machines: Windows, Mac, and Linux. It works on all 3.

What about the other questions I asked?

**Comment by kmarray98** [comment]
On the first  - here are the outputs extending your example above
The following code (added to the code above)
datasummary_skim(df)
m1 <- lm(foo~searchperiod, data=df)
modelsummary(m1)
 returns the following tables
![Rplot_1](https://user-images.githubusercontent.com/77078860/132821712-df3829c3-0e46-4aa8-8604-de9fbf731df1.png)
![reprex_2](https://user-images.githubusercontent.com/77078860/132821704-6e14efbc-9832-43bf-a1cb-6a544eb1c5b4.png)

Nothing changes for me if I change the output argument

**Comment by vincentarelbundock** [comment]
What about when you set the `output` argument of `datasummary_balance` to "data.frame" ?
