### ISSUE TITLE
Missing values in Datasummary

### ISSUE THREAD

**Issue by basm92** [vincentarelbundock/modelsummary#379]
Hi,

I was using the modelsummary::datasummary function to create a grouped summary table, but I stumbled upon the problem that if there are no observations for one group, the datasummary function's default behavior is to create a blank cell, without leaving the user the option to change the cell into "NA", or anything custom.

Example:

```{r}
datasummary(data = mtcars %>%
                 mutate(carb = as.factor(carb), vs = as.factor(vs)), formula = carb ~ vs * wt*Mean)
```

I attempted to bypass this behavior, again, for example, by means of this:

```{r}
custom_mean <- function(x){
    if(is.null(x) || is.na(x)){ return("N.A.") } else {mean(x, na.rm = TRUE)}}

datasummary(data = mtcars %>%
                 mutate(carb = as.factor(carb), vs = as.factor(vs)), formula = carb ~ vs * wt*custom_mean)

```

But unfortunately, to no avail. Do you know of any way to implement this compatible with the datasummary function, or  could it be possible to implement such an option?

Thanks a lot for your effort!

**Comment by vincentarelbundock** [comment]
Do any of the solutions documented here work for you?

https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#missing-values-1

**Comment by vincentarelbundock** [comment]
Aaaaah! I see what you mean. Sorry, I read this too quickly initially.

Yes, the issue is that we do a dumb substitution of "NA" to "" so the table looks prettier, but unfortunately this means that if you just leave "NA" in there it will get replace.

I think your solution is pretty straightforward, and probably the best we can do without considerable infrastructure change.

Thanks for the report and for posting your solution!
