### ISSUE TITLE
Report odds ratio with modelsummary

### ISSUE THREAD

**Issue by Cami1992** [vincentarelbundock/modelsummary#382]
Hi, I would love to know how I can report my odd ratios for each of my models as in stargazer.

allmodels<- list("Model 1" = OR_001, "Model 2" = OR_003, "Model 3" = OR_05)
coefs_t5 <- c('DEP'= 'Traditional=1 and Liberal =0', 'INCOMEHigh income'='High income', 'INCOMELow income'='Low income', 'edudummyLow education'='Low education', 'edudummyHigh education'='High education','RELIGIONImportant'='Religion is important', 'RELIGIONNo important'='Religion is not important' )
caption <-  'Table : Survey experiment results, ordinal logistic results on restrictionist immigration preferences'
model_t5 <- modelsummary( allmodels, output="kableExtra", coef_map= coefs_t5, title =caption)
 model_t5 %>%
   add_header_above(c(" " =1, "Full Sample" =2, "Not retired"= 1, "Retired" =1))%>%
   footnote(general = 'Note: includes age, income, education, and religion dummy variables;
          p < 0.05; **p < 0.01; **p < 0.001. Standard errors are robust.')

stargazer(model_003, model_05, coef = list(OR_003, OR_05), t.auto=F, p.auto=F,type="text",report = "vc*", star.cutoffs = c(0.05, 0.01, 0.001), notes.append = F, digits = 3, notes ="Model 1 includes Age and Income dummy variables. Model 2 adds Education. Model 3 reports religion; *p < 0.05; **p < 0.01; ***p < 0.001.", covariate.labels = c("Age 30-59", "Age 60-59", "High income", "Low income", "High education", "Low education","Important", "No important", "Constant"), title = "Table 4: Model 1 , Model 2 and Model 3", dep.var.labels = "Attitudes towards homosexual neighbors: 1= Traditional, 0= Liberal", dep.var.caption = "Results from Logistic Regression, Odds Ratios" , align = T)

**Comment by vincentarelbundock** [comment]
This question is hard to answer because (a) I don't know what `stargazer` does, and (b) I don't know the `OR_001` and other models in your example are.

Do you just want to exponentiate the coefficients, as described here? https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#exponentiated-coefficients-and-other-extras-

**Comment by vincentarelbundock** [comment]
FYI, I wrote a whole new section on the website on how to do that, and why things are how they are. Bottom line:

1. There are good statistical reasons to report confidence intervals instead of standard errors
2. You can do: `modelsummary(model, exponentiate = TRUE, statistic = "conf.int")`
3. If you want to report standard errors instead of confidence intervals, you can adopt one of 2 easy strategies described on the website.

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#exponentiated-coefficients-and-other-extras-
