### ISSUE TITLE
Wrong "ALL" column total added values for some rows?

### ISSUE THREAD

**Issue by sfd99** [vincentarelbundock/modelsummary#410]
REF EX in Twitter:
https://twitter.com/rfunctionaday/status/1459401974571544582?s=20

Spectacular & easy PKG!.

But (somehow), 
some values of the _ALL_ column (last),
don't add up with the row values.

ex:
for **GENTOO** row,
 58 + 61 =  119 (not 124).

The **CHINSTRAP** _ALL_ column value is ok...
34+34=68 OK.

Pls,  do correct me if I'm wrong!.
Maybe, I'm misunderstood
the purpose of the _ALL_ last column..

**Comment by vincentarelbundock** [comment]
There are `NA`s in the `penguins` dataset. The `All` column follows the `tables` package convention of counting all rows in the dataset. You can change this behavior by creating your own summary using the `datasummary` function, which is way more flexible: https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html

**Comment by sfd99** [comment]
Ah, understood Vincent...

A humble suggestion:
(if I may...)

 any way to add a 
   na.omit = T (by default)
parameter  to
datasummary_crosstab() ?.

That would be really helpful (I think)
to avoid forgetting possible NAs in a DF...

**Comment by vincentarelbundock** [comment]
> A humble suggestion: (if I may...)
> 
> any way to add a **na.omit = T** (by default) parameter to datasummary_crosstab() ?.
> 
> That would be really helpful (I think) to avoid forgetting possible NAs in a DF...

All suggestions are most welcome!!

I see where you are coming from with this, but I'm not convinced that it is a good idea.

1. In general, I strongly prefer to *not* modify the user data unless the user has explicitly asked for it. Having a default of `na.omit=TRUE` would contradict this principle, since calling a simple `datasummary_crosstab(x~y)` would modify the data even if the user didn't write code to ask for it explicitly.
2. One of the overriding design goals of the `modelsummary` package is to keep functions very simple, with as few arguments as possible. The `stargazer` function has a similar purpose, but has 85 arguments! I'm trying to be very lean.
3. These two options use about the same number of characters:

```r
datasummary_crosstab(y ~ x, data = na.omit(df))
datasummary_crosstab(y ~ x, data = df, na.omit = TRUE)
```

So while I really appreciate your suggestion, I don't think I'm going to implement it right now, unless I see a clear and compelling use-case for it.

**Comment by sfd99** [comment]
Yes,
I clearly see your points.
Love your PKG!.

_Merci / Thanks Vincent!._

SFd
San Francisco

**Comment by vincentarelbundock** [comment]
Thanks for understanding!
