### ISSUE TITLE
Allow datasummary_balance (or provide equivalent) to describe full sample

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#434]
The table provided by datasummary_balance would seem to be helpful in many instances when it comes to describing the full sample (rather than subgroups). So I would love to be able to run `datasummary_balance(~1, mtcars)` or something like that - but that fails. Could that be allowed? Or am I overlooking such functionality in another `datasummary_` function?

(If it is indeed missing and you agree that this would be a helpful extension, I would be happy to look into how to implement it.)

**Comment by vincentarelbundock** [comment]
You're right: this is not currently supported. It would be a neat feature!

A warning before you dive too deep: the `datasummary_balance` code is quite finicky. The problem is that `datasummary` relies on the `tables::tabular` function to do all the heavy lifting behind the scene. But one important limitation of this package/function is that it doesn't provide an easy way to combine summaries for factor and numeric variables. So I ended up writing a bunch of hacks: first I create two tables for numeric and factors, then I align and stack the two tables on top of each other.

It's definitely not impossible, but it probably won't be a 2-line change either. A change would probably have to involved detecting the "special" formula `~1` and then modifying the `f_fac` and `f_num` formulas by removing their `Factor(%s)` component:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/datasummary_balance.R#L97
https://github.com/vincentarelbundock/modelsummary/blob/main/R/datasummary_balance.R#L119
https://github.com/vincentarelbundock/modelsummary/blob/main/R/datasummary_balance.R#L127

This might work immediately, or the alignment might have to be tweaked after. Not sure. I'm pretty sure the headers will have to be adjusted (or removed entirely):

https://github.com/vincentarelbundock/modelsummary/blob/main/R/datasummary_balance.R#L180

**Comment by vincentarelbundock** [comment]
Thanks again for this!
