### ISSUE TITLE
If you set options(modelsummary_get = "easystats"), then R^2 is labelled as "estimate" in subsequent call w/ metrics = "all" or metrics = "common"

### ISSUE THREAD

**Issue by michelledion** [vincentarelbundock/modelsummary#441]
I wanted to include RMSE in the model summary section of a model. My understanding (based on the documentation) is that to get access to RMSE, I need to first set the option for modelsummary_get. But then, when I call modelsummary() with the option metrics = "common" or metrics = "all" the result includes RMSE (like I want) but now the R^2 is mislabelled estimate & appears at the bottom of the table. 

(Of course, I could hand code the glance object but I'm trying to use this package for teaching, and this misbehavior is unintended and is creating confusion for my students. 

Here's a repex.  

```r
library(modelsummary)
library(kableExtra)
m1 = lm(dist ~ speed, data = cars)
# works like it should 
modelsummary(m1, metrics = "common")
# works like it should 
modelsummary(m1, metrics = "all")
# follow guidance on website to get the RMSE
options(modelsummary_get="easystats")
# now call 
modelsummary(m1, metrics = "all")
# R^2 is now labelled "estimate"
modelsummary(m1, metrics = "common")
# and again, and it's at the bottom of the list
```

**Comment by vincentarelbundock** [comment]
Thanks for the report\!

There is in fact a bug, but it is in an upstream package (i.e., a
dependency). I can submit a pull request there to fix it, but it might
take a month or two before it reaches CRAN.

Here’s a long explanation. Scroll all the way down for two alternatives
to tide you over until the upstream bug is fixed.

The first thing to note is that `{modelsummary}` can use two packages to
extract goodness of fit statistics: `{broom}` (the default) and
`{performance}`. As you suggests, `{broom}` doesn’t extract the RMSE,
but `{performance}` does:

``` r
library(modelsummary)

m1 = lm(dist ~ speed, data = cars)

broom::glance(m1)
```

    ## # A tibble: 1 × 12
    ##   r.squared adj.r.squared sigma statistic  p.value    df logLik
    ##       <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl>
    ## 1     0.651         0.644  15.4      89.6 1.49e-12     1  -207.
    ## # … with 5 more variables: AIC <dbl>, BIC <dbl>,
    ## #   deviance <dbl>, df.residual <int>, nobs <int>

``` r
performance::performance(m1)
```

    ## # Indices of model performance
    ## 
    ## AIC     |     BIC |    R2 | R2 (adj.) |   RMSE |  Sigma
    ## -------------------------------------------------------
    ## 419.157 | 424.893 | 0.651 |     0.644 | 15.069 | 15.380

If we want the RMSE, we need to use `performance` with the global
option:

``` r
options(modelsummary_get = "performance")
```

The problem in `{performance}` comes when we try to rename the columns:

``` r
lm(dist ~ speed, data = cars) |>
    performance::performance() |>
    insight::standardize_names(style = "broom")
```

    ##        aic      bic  estimate r2.adjusted     rmse    sigma
    ## 1 419.1569 424.8929 0.6510794   0.6438102 15.06886 15.37959

You see that `r2` gets mistakenly renamed `estimate`. Someone (probably me) will need to
patch to this in the `{insight}` package in order to fix the problem. I have already filed a bug
report here: <https://github.com/easystats/insight/issues/511>

Note that in this context, the `metrics` argument doesn’t do much. It is only really useful
for bayesian or mixed effects models where there are a lot of
alternative GOFs and when some of them are expensive to compute.

What to do until then this is fixed and published?

# Option 1: `gof_map` argument

Create a data.frame to specify which determines which goodness of fit
statistiques you want to use. I use `tribble` for convenience:

``` r
gm <- tibble::tribble(
  ~raw,       ~clean, ~fmt,
   "estimate", "R2",   2,
   "rmse",     "RMSE", 3)

modelsummary(m1, gof_map = gm)
```

|             | Model 1  |
| :---------- | :------: |
| (Intercept) | \-17.579 |
|             | (6.758)  |
| speed       |  3.932   |
|             | (0.416)  |
| R2          |   0.65   |
| RMSE        |  15.069  |

# Option 2: `tidy_custom.lm()` method

This option seems a bit more complicated, but the beauty is that once
you’ve loaded this function in your environment, the `RMSE` should
always appear automatically:

``` r
glance_custom.lm <- function(x) {
    data.frame("r.squared" = summary(x)$r.squared)
}

modelsummary(m1)
```

|             | Model 1  |
| :---------- | :------: |
| (Intercept) | \-17.579 |
|             | (6.758)  |
| speed       |  3.932   |
|             | (0.416)  |
| Num.Obs.    |    50    |
| R2          |  0.651   |
| R2 Adj.     |  0.644   |
| AIC         |  419.2   |
| BIC         |  424.9   |
| F           |  89.567  |
| RMSE        |  15.07   |
| estimate    |  0.651   |

**Comment by vincentarelbundock** [comment]
@michelledion, you can ignore my long previous post. Everything in there
is still accurate, but I decided to implement a workaround.

The next version of `{modelsummary}` will include RMSE by default for
`lm()` models. It is on its way to CRAN now.

Until it gets there (usually 24-72h), you can try the Github devel version:

``` r
remotes::install_github("vincentarelbundock/modelsummary")
```

Restart R completely. Then,

``` r
library(modelsummary)
mod <- lm(mpg ~ hp, mtcars)
modelsummary(mod)
```

|             | Model 1  |
| :---------- | :------: |
| (Intercept) |  30.099  |
|             | (1.634)  |
| hp          | \-0.068  |
|             | (0.010)  |
| Num.Obs.    |    32    |
| R2          |  0.602   |
| R2 Adj.     |  0.589   |
| AIC         |  181.2   |
| BIC         |  185.6   |
| Log.Lik.    | \-87.619 |
| F           |  45.460  |
| RMSE        |   3.86   |

**Comment by michelledion** [comment]
Thanks, @vincentarelbundock! I will be sure to update. 

I read the minimized comment to better understand how your pkg works under the hood. 

At least in lm(), the sigma in glance() is always the same as the RMSE in modelsummary(), and in some textbooks the RMSE is introduced as sigma-hat, the standard deviation of the conditional distribution of Y. [I show my students both ways... for their reference.] So, for lm(), I don't think you have to use the model_performance(), unless you want the AIC, BIC, & Log.Lik. 

Either way, thanks for the fix! This will hopefully avoid some student confusion. :)

**Comment by vincentarelbundock** [comment]
> At least in lm(), the sigma in glance() is always the same as the RMSE in modelsummary(), and in some textbooks the RMSE is introduced as sigma-hat, the standard deviation of the conditional distribution of Y. [I show my students both ways... for their reference.] So, for lm(), I don't think you have to use the model_performance(), unless you want the AIC, BIC, & Log.Lik.

Yes, that's exactly right. The new version of `{modelsummary}` uses the `sigma()` function from Base `R` to add the RMSE to `lm()` models, so we don't need to call on `model_performance()` at all.

Don't hesitate to ping me if you run into other issues. I've found that students are often best at identifying problems and counter-intuitive behavior in software, so this is super useful.

Cheers!
