### ISSUE TITLE
Exponentiate doesn't work with clustered standard errors

### ISSUE THREAD

**Issue by wrahool** [vincentarelbundock/modelsummary#445]
I am trying to output the results of negative binomial regression models, and am able to get the confidence intervals associated with the clustered standard errors by using the `vcov = ~clustering_variable` parameter. However, when I try to get the IRRs (or incidence rate ratios) by exponentiating the estimates:

`modelsummary(mod, statistic = "conf.int", exponentiate = TRUE, vcov = ~clustering_variable)`

the raw estimates are shown (and not the exponentiated estimates and CIs. Is it at all possible to get the exponentiation to work with clustered standard errors?

**Comment by vincentarelbundock** [comment]
Thanks for reporting the issue\!

Background: The problem is that `exponentiate` is an argument passed
through the `...` to the `broom::tidy()` function, which is used to
extract information from the models. In contrast, `vcov` is an argument
handled by `modelsummary` *after* the estimates were already extracted.

This is a common use-case, so I need to think of a better long term
solution. In the meantime, you can use the `fmt` argument as follows:

``` r
library(modelsummary)
mod <- glm(am ~ hp + mpg, data = mtcars, family = binomial)
modelsummary(mod,
             vcov = ~cyl,
             statistic = "conf.int",
             fmt = function(x) sprintf("%.3f", exp(x)))
```

|             |     Model 1      |
| :---------- | :--------------: |
| (Intercept) |      0.000       |
|             | \[0.000, 0.000\] |
| hp          |      1.057       |
|             | \[1.028, 1.086\] |
| mpg         |      3.524       |
|             | \[1.720, 7.218\] |
| Num.Obs.    |        32        |
| AIC         |       25.2       |
| BIC         |       29.6       |
| Log.Lik.    |     \-9.616      |
| Std.Errors  |     by: cyl      |

Note that this will *not* work for standard errors, since you need to
use a `exp(b)*se` for those. See discussion here:
<https://github.com/vincentarelbundock/modelsummary/issues/445>

If you need exponentiated standard errors, you will probably need to
create a `tidy_custom.glm` method, as discussed in the documentation:
<https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i>

Again, I know this is a common use-case, so I will try to implement a
better strategy, possibly by adding my own `exponentiate` argument
instead of relying on `broom`.

**Comment by vincentarelbundock** [comment]
I have now added “official” support for the `exponentiate` argument. It
should behave as expected (my previous comment is now hidden because it is obsolete):

``` r
library(modelsummary)
mod <- glm(am ~ hp + mpg, data = mtcars, family = binomial)

coef(mod)
```

    ##  (Intercept)           hp          mpg 
    ## -33.60517103   0.05504458   1.25961463

``` r
exp(coef(mod))
```

    ##  (Intercept)           hp          mpg 
    ## 2.543664e-15 1.056588e+00 3.524063e+00

``` r
modelsummary(mod,
             vcov = list("classical", "robust", ~cyl),
             exponentiate = TRUE,
             statistic = c("std.error", "conf.int"))
```

|             |      Model 1      |     Model 2      |     Model 3      |
| :---------- | :---------------: | :--------------: | :--------------: |
| (Intercept) |       0.000       |      0.000       |      0.000       |
|             |      (0.000)      |     (0.000)      |     (0.000)      |
|             | \[0.000, 0.000\]  | \[0.000, 0.000\] | \[0.000, 0.000\] |
| hp          |       1.057       |      1.057       |      1.057       |
|             |      (0.028)      |     (0.024)      |     (0.015)      |
|             | \[1.017, 1.133\]  | \[1.010, 1.105\] | \[1.028, 1.086\] |
| mpg         |       3.524       |      3.524       |      3.524       |
|             |      (2.000)      |     (1.505)      |     (1.289)      |
|             | \[1.607, 15.969\] | \[1.526, 8.140\] | \[1.720, 7.218\] |
| Num.Obs.    |        32         |        32        |        32        |
| AIC         |       25.2        |       25.2       |       25.2       |
| BIC         |       29.6        |       29.6       |       29.6       |
| Log.Lik.    |      \-9.616      |     \-9.616      |     \-9.616      |
| F           |       2.467       |      4.427       |                  |
| RMSE        |       0.81        |                  |                  |
| Std.Errors  |     Classical     |      Robust      |     by: cyl      |

This will be part of the next release on CRAN, but in the meantime you
can install it from Github:

``` r
remotes::install_github("vincentarelbundock/modelsummary")
```

Make sure you restart R completely for the changes to take effect.

**Comment by wrahool** [comment]
great, thanks!
