### ISSUE TITLE
`coef_keep` argument

### ISSUE THREAD

**Issue by rgerecke** [vincentarelbundock/modelsummary#468]
thanks for the great package! has become my go-to for visualizing linear model results. would love to see an added argument `coef_keep`, where I could specify a regex for coefficients i'd like to keep rather than ones i'd like to get rid of. negating a regex is so complicated :( `coef_map` sort of allows for this but isn't quite what i'm looking for.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the suggestion, I really appreciate it!

To give you a bit of background, one of the main reasons I developed `modelsummary` is that I grew frustrated with `stargazer`, which offers a similar function with EIGHTY-FIVE (85!) arguments. It just felt so overwhelming that I decided to do something simpler. Since then, I've tried to be absolutely ruthless about adding new arguments.

Currently, we can supply full term names:

```{r}
library(modelsummary)

mod <- lm(mpg ~ hp + drat + wt + factor(cyl), mtcars)

modelsummary(mod, coef_map = c("hp", "drat"), output = "markdown")
```

Match the first few letters:

```{r}
modelsummary(mod, coef_omit = "^(?!h|dr)", output = "markdown")
```

Match a single substring like `"pt"`:

```{r}
modelsummary(mod, coef_omit = "^(?!.*pt)", output = "markdown")
```

Match two substrings:

```{r}
modelsummary(mod, coef_omit = "^(?!.*pt|.*ra)", output = "markdown")
```


Frankly, I'm not (yet) 100% convinced that we need a whole new argument for that. I'm still open to an argument, but wonder if improving the documentation might solve this "problem".

We could also return an informative error with some examples if users supply a regex that matches no rows at all (a sign that they tried something weird).

**Comment by vincentarelbundock** [comment]
FYI, I just pushed an update to the development version on Github with improved documentation. There are now several working examples in the Examples section of `?modelsummary`, and the `coef_omit` argument is documented as follows:

![coef_omit](https://user-images.githubusercontent.com/987057/164911854-5255e5a0-455f-483a-aba5-f138abb9e10a.jpg)

If a user tries to use a weird regex and ends up omitting all the coefficients, we now get an informative error message. For example, here we forgot the `^` hat at the start of the regex:

``` r
library(modelsummary)
mod <- lm(mpg ~ hp + drat, data = mtcars)

modelsummary(mod, coef_omit = "(?!.*d)", output = "markdown")
#> Error: The regular expression supplied to `coef_omit` matched and omitted all the coefficients, but `modelsummary` requires at least one coefficient to produce a table. Here are some examples of valid regular expressions for different use-cases:
#> 
#> library(modelsummary)
#> data(trees)
#> mod <- lm(Girth ~ Height + Volume, data = trees)
#> 
#> # coef_omit: omit coefficients matching one substring
#> modelsummary(mod, coef_omit = "ei")
#> 
#> # coef_omit: omit a specific coefficient
#> modelsummary(mod, coef_omit = "^Volume$")
#> 
#> # coef_omit: omit coefficients matching either one of two substring
#> modelsummary(mod, coef_omit = "ei|rc")
#> 
#> # coef_omit: keep coefficients starting with a substring (using a negative lookahead)
#> modelsummary(mod, coef_omit = "^(?!Vol)")
#> 
#> # coef_omit: keep coefficients matching either one of two substring
#> modelsummary(mod, coef_omit = "^(?!.*ei|.*pt)")
```

**Comment by rgerecke** [comment]
Thanks for the quick & helpful explanation! The regex documentation is a good compromise. One could argue about whether `coef_keep` vs `coef_omit` is more useful if you can only choose one....but I will not be doing that to you, haha.

**Comment by vincentarelbundock** [comment]
Hehe!

:)
