### ISSUE TITLE
Goodness of fit table

### ISSUE THREAD

**Issue by gtobin26** [vincentarelbundock/modelsummary#476]
How can I adjust the number of decimal places in the GOF table, e.g. RMSE? I want to increase RMSE from two to four.

**Comment by vincentarelbundock** [comment]
Use the `gof_map` argument. See the docs:

https://vincentarelbundock.github.io/modelsummary/reference/modelsummary.html

**Comment by gtobin26** [comment]
Thx. That works. Having run it with 'RMSE', I suspect that RMSE in 'modelsummary' may be RSD. sigma in 'glance' is RSD (sometimes incorrectly described as RSE even in the R lm package).  RDocumentation states that "sigma is the estimated standard deviation of the errors, the “residual standard deviation” (misnamed also “residual standard error”." I haven't found any way yet of including both RSD and RMSE in a regression summary. If you have a solution, I would love to hear it.

**Comment by vincentarelbundock** [comment]
Yes, this is a known bug and it is already fixed in the development version of `modelsummary`. You can install from Github and restart R. After that it should work fine.

Sorry for the mislabeling.

There are detailed instructions on the website on how to add statistics that are not there by default:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-information-to-existing-models

**Comment by gtobin26** [comment]
No problem. I'll give both of those suggestions a try. You have probably gathered that I am not very proficient in R! Modelsummary is a nice add on to R. Thank you

**Comment by vincentarelbundock** [comment]
very happy you like it!
