### ISSUE TITLE
Problems with table title and float in knitr pdf output

### ISSUE THREAD

**Issue by ashirwad** [vincentarelbundock/modelsummary#48]
Hello, 

Thanks for this wonderful package! I started using the package recently and found some problems that I thought I should bring to your attention.

1.  `title` argument in the `msummary()` function does not seem to have an effect in the `knitr` pdf output.
1. The table does not float and breaks across pages in the final output.

Thanks!

**Comment by vincentarelbundock** [comment]
Thanks a lot for the bug report @ashirwad !!

1. I think this bug was fixed in a previous commit. Have you tried reinstalling from Github? `remotes::install_github('vincentarelbundock/modelsummary')`

2. This is probably because `gt` uses the `longtable` LaTeX environment to typeset tables. This environment automatically splits over pagebreaks. I modified the `knit_latex` function to take a `latex_env='table'` argument, which switches it back to the normal table > tabular set up. This should float instead of break. I paste a Rmarkdown example below. It compiles fine on my machine with the Github master version.

Please note that the `knit_latex` function is a horrrrible hack. The fundamental issue is that LaTeX output under `gt` is not mature yet. I expect things to improve a lot when the `gt` team starts putting new effort into it.

In the meantime, please let me know if the solution I proposed works for your application.

Thanks!


````
---
output: pdf_document
header-includes: 
  - \usepackage{caption}
  - \usepackage{longtable}
  - \usepackage{booktabs}
---

Table \ref{test_label} shows two models.

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# load
library(dplyr)
library(modelsummary)

# simulate data
x <- rnorm(30)
w <- rnorm(30)
y <- x + w + rnorm(30)

# fit models
mod <- list()
mod[[1]] <- lm(y ~ x)
mod[[2]] <- lm(y ~ x + w)

# summarize
msummary(mod, title = 'Test title') %>%
    knit_latex(label = 'test_label', latex_env = 'table')
```  
````

**Comment by ashirwad** [comment]
Thanks, @vincentarelbundock! Everything seems to be working now. :)

**Comment by vincentarelbundock** [comment]
Wonderful!
