### ISSUE TITLE
Smarter detection of glue strings

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#497]
By default, `statistic` is set to show standard errors in a new line. When I use the `estimate` argument to add SEs to the same line, I get the SEs twice.

It's not high priority, but would be a nice feature, to check the input of `estimate` against `statistic` and remove duplicates (preferably, keep `estimate` settings):

```r
m1 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
m2 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris)
m3 <- lme4::lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris)

modelsummary::modelsummary(model, estimate  = "{estimate} ({std.error})", 
                           shape = group + term + statistic ~ model,
                           fmt = 2)
```

![image](https://user-images.githubusercontent.com/26301769/172548033-727e202a-cfe9-409a-bfec-e4969a929dd6.png)

**Comment by vincentarelbundock** [comment]
Hmm, this is interesting, but I'm not quite convinced (yet!).

In general, I think it's probably better to be more explicit, rather than auto-magical, and to do exactly what the user has requested. Here, we have `statistic="std.error"`, so I think it's normal to expect it to return the standard error in the statistic spot. Setting `statistic=NULL` doesn't seem like a huge cost.

But I do understand how this could be convenient, so I'm open to counter-arguments and will keep thinking about it.
