### ISSUE TITLE
cluster SE using `vcov` parameter

### ISSUE THREAD

**Issue by jialul** [vincentarelbundock/modelsummary#518]
Hi! I am trying to summarise model outputs from `polr` using clustered SE but noticed that clustered SE was not reflected in `modelsummary` and `get_estimates`. They give the same SE estimates either with or without "vcov = ~ clusterid".

**Comment by vincentarelbundock** [comment]
Thanks a lot for the bug report\! In principle this should not be fixed in the devel version on Github. Make sure you restart R after installing and before trying.

``` r
library(MASS)
library(modelsummary)
mod <- polr(factor(gear) ~ mpg, data = mtcars)
modelsummary(mod, output = "markdown", vcov = list(NULL, ~cyl))
#> 
#> Re-fitting to get Hessian
#> Warning: 
#> The `lmtest::coeftest` function does not seem to produce complete results when
#> applied to a model of class polr. Only the standard errors have been adjusted. p
#> values and confidence intervals may not be correct.
```

|            | Model 1 | Model 2 |
| :--------- | :-----: | :-----: |
| 3 / 4        |  3.709  |  3.709  |
|            | (1.424) | (0.692) |
| 4 / 5        |  6.012  |  6.012  |
|            | (1.708) | (1.075) |
| mpg        |  0.188  |  0.188  |
|            | (0.067) | (0.018) |
| Num.Obs.   |   32    |   32    |
| AIC        |  61.3   |  61.3   |
| BIC        |  65.7   |  65.7   |
| RMSE       |  3.44   |  3.44   |
| Std.Errors |         | by: cyl |

Closing this issue now, but feel free to comment further or re-open if this doesn’t work for you.

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jialul** [comment]
Thanks! I updated the package with the github version and it works now.
