### ISSUE TITLE
Labelled data support

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#542]
Most functions in the `modelsummary` package will now use variable labels automatically.

To do this, we need a function which takes a data frame and returns a named vector of variable names and labels.

@strengejacke, in your experience, will this function retrieve labels from all major types? (`haven`, `sjlabelled`, etc.)

Thanks!

```
get_variable_labels_data <- function(data) {
    # global variables: sjlabelled-style
    lab <- attr(data, "label", exact = TRUE)
    # variable attributes: haven-style
    if (is.null(lab)) {
        lab <- Filter(
            function(x) inherits(data[[x]], c("labelled", "haven_labelled")),
            colnames(data))
        lab <- sapply(lab, function(x) attr(data[[x]], "label"))
    }
    if (length(lab) == 0) {
        lab <- NULL
    }
    return(lab)
}
```

**Comment by strengejacke** [comment]
packages like _sjlabelled_ or _labelled_ just retrieve the `label` and `labels` attributes that are used by _haven_.
If you assume _haven_ is the most used package to import foreign data, you can easily retrieve labels via

```r
value_labels <- attr(x, "labels", exact = TRUE)
variable_labels <- attr(x, "label", exact = TRUE) # I would use "exact" here, else you get value labels when no variable label present
```

This will return `NULL` for unlabelled data of course, so no need to check for the class attribute.

The _foreign_ package attaches variable label as attribute to the data frame. I had support for this in _sjlabelled_, but dropped this sometime in the past because my impression was that it's not used that often anymore (since most packages that import data rely on _haven_).

**Comment by vincentarelbundock** [comment]
Thanks, this is very useful!

**Comment by strengejacke** [comment]
You can look at the code here: https://github.com/strengejacke/sjlabelled/blob/513ded296f6119c72cd6c5694a2ea4fdf3610c67/R/get_label.R#L80

This returns a named vector with column names and associated label attributes. If you use `def.value = colnames(x)`, you will always get a value, either the label, or the column name if no value present. I think this is one good way to extract labels.
