### ISSUE TITLE
gof_map argument for `fixest::feglm()`

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#574]
The documentation says: 

> A more powerful mechanism is to supply a data.frame (or tibble) through the gof_map argument. This data.frame must include 3 columns: raw: a string with the name of a column produced by broom::glance(model).

But when I run the following, I do not see a clear logic. In fact, the BIC seems to reported wrong.

```r
mtcars |> fixest::feglm(vs ~ mpg)
# GLM estimation, family = gaussian, Dep. Var.: vs
# Observations: 32 
# Standard-errors: IID 
#             Estimate Std. Error  t value   Pr(>|t|)    
# (Intercept) -0.678165   0.243096 -2.78971 9.0786e-03 ** 
# mpg          0.055532   0.011605  4.78528 4.2693e-05 ***
# ---
# Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
# Log-Likelihood: -14.7   Adj. Pseudo R2: 0.346393
#           BIC:  36.3     Squared Cor.: 0.440948

mtcars |> fixest::feglm(vs ~ mpg) |> broom::glance() |> str()
tibble [1 × 9] (S3: tbl_df/tbl/data.frame)
 $ r.squared       : num NA
 $ adj.r.squared   : num NA
 $ within.r.squared: num NA
 $ pseudo.r.squared: num 0.388
 $ sigma           : num NA
 $ nobs            : int 32
 $ AIC             : num 33.3
 $ BIC             : num 36.3
 $ logLik          : num -14.7

mtcars |> fixest::feglm(vs ~ mpg) |> modelsummary(gof_map =  list(list("raw" = "pseudo.r.squared",  "clean" = "Pseudo-R2",  "fmt" = 3)), output = 'dataframe')
       part        term statistic Model 1
1 estimates (Intercept)  estimate  -0.678
2 estimates (Intercept) std.error (0.243)
3 estimates         mpg  estimate   0.056
4 estimates         mpg std.error (0.012)

mtcars |> fixest::feglm(vs ~ mpg) |> modelsummary(output = 'dataframe')
        part        term statistic Model 1
1  estimates (Intercept)  estimate  -0.678
2  estimates (Intercept) std.error (0.243)
3  estimates         mpg  estimate   0.056
4  estimates         mpg std.error (0.012)
5        gof    Num.Obs.                32
6        gof          R2             0.388
7        gof     R2 Adj.             0.346
8        gof         AIC              35.3
9        gof         BIC              39.7
10       gof        RMSE              0.37
11       gof  Std.Errors               IID
```

**Comment by vincentarelbundock** [comment]
Sorry, can't check right now, but the vignette appears to be out of date. As noted in the `?modelsummary` docs, the GOF names are *not* those produced by `broom`, but rather those produced by `get_gof(model)`. This is because we now use the `performance` package to extract GOF statistics instead of `broom`, because it supports way more models.

Let me know if the column names of `get_gof(model)` don't work.

**Comment by statzhero** [comment]
Not too worried about the documentation, but do check out why / if the BIC above is different. 

In my case (sorry can't share more) `est_gro` is a list of `fixest` models. 

```r
# fixest::feols() with no fixed effects
get_gof(est_gro[[1]])
      aic     bic    r.squared adj.r.squared     rmse   nobs
1 1780167 1780264 0.0002849249  0.0002643491 3.313549 340118
  vcov.type
1 by: nace2

# fixest::feols() with fixed effects
get_gof(est_gro[[2]])
      aic     bic     rmse   nobs FE: nace2 FE: nuts2
1 1779729 1779815 3.311427 340118         X         X
  FE: factor(year) vcov.type
1                X by: nace2

# fixest::feglm() with fixed effects
get_gof(est_gro[[3]])
       aic      bic       rmse   nobs FE: nace2 FE: nuts2
1 5413.772 5488.637 0.03381006 326098         X         X
  FE: factor(year) vcov.type
1                X by: nace2
```

**Comment by vincentarelbundock** [comment]
Are those different from the results obtained simply using `stats::AIC` or `stats::BIC`?

BTW, you must be using a very old version of all the packages, because in the latest version of `modelsummary` and `performance`, there is no BIC or AIC included at all for `fixest` models. 

I just opened a Pull Request on the `performance` repository to add support for that statistic in `fixest`. See here: https://github.com/easystats/performance/pull/514

You can normally install the very latest versions using the code here:

https://github.com/vincentarelbundock/modelsummary#installation

**Comment by vincentarelbundock** [comment]
Ah yeah, that makes sense.

FYI, my patch was already merged in `performance`. If you install that package from Github, you should get correct BIC and AIC automatically.

**Comment by vincentarelbundock** [comment]
https://github.com/easystats/performance
