### ISSUE TITLE
Question/FR: Invisibilizing "`shape`" columns

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#629]
I will try to explain with an example.
```r
mtcars <- transform(mtcars, cyl = as.factor(cyl), vs = as.factor(vs), am = as.factor(am))
m1 <- glm(am ~ cyl, data = mtcars, family = binomial)
m2 <- glm(am ~ vs, data = mtcars, family = binomial)
modelsummary(list(cyl = m1, vs = m2), coef_rename = TRUE, output = "markdown", shape = model + term ~ statistic, coef_omit = "Intercept")


|     |         |  Est.  |  S.E. | 
|:----|--------:|-------:|------:|
| cyl | cyl [6] | -1.269 | 1.021 | 
|     | cyl [8] | -2.773 | 1.021 | 
| vs  | vs [1]  |  0.693 | 0.732 | 
```
Let's say I have many simple models with the same outcome, each one with a different dependent variable, and I want to have them as rows, while statistics as columns. In the example one can see that the `term` column already gives all the necessary information. Is there some way to remove or make invisible the model column?

Thank you!

**Comment by iago-pssjd** [comment]
Related to this, generalizing this question, is it possible to remove the model name of the printed object. For example, for
```r
data(trees)
models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees)

# simple table
modelsummary(models, output = "markdown")
```
the header row with Bivariate and Multivariate would be removed. Here may not have sense, but when there is a unique model without name, the default `(1)` could be removable (and it is even more annoying if the output is "kableExtra").

|             | Bivariate | Multivariate | 
|:------------|----------:|-------------:|
| (Intercept) |   -6.188  |    10.816    | 
|             |  (5.960)  |    (1.973)   | 
| Height      |   0.256   |    -0.045    | 
|             |  (0.078)  |    (0.028)   | 
| Volume      |           |     0.195    | 
|             |           |    (0.011)   | 
|:------------|----------:|-------------:|
| Num.Obs.    |     31    |      31      | 
| R2          |   0.270   |     0.941    | 
| R2 Adj.     |   0.244   |     0.937    | 
| AIC         |   154.1   |     78.2     | 
| BIC         |   158.4   |     84.0     | 
| Log.Lik.    |  -74.061  |    -35.116   | 
| F           |   10.707  |    222.471   | 
| RMSE        |    2.64   |     0.75     |

**Comment by vincentarelbundock** [comment]
There is currently no mechanism to remove columns automatically. You can first call `modelsummary(output = "dataframe")`, remove the columns you don't want, and then feed the result to `datasummary_df()`. This should be quite easy.

You can assign empty strings to the names of the list to get empty headers. 

Removing the header completely cannot be done with `modelsummary`, because `modelsummary` does not draw the tables itself. There is a chance that one of the table-making packages that `modelsummary` supports can do this (`kableExtra`, `gt`, `flextable`, etc.), but I am not aware of such an option. Please refer to their documentation.
