### ISSUE TITLE
Include both labels for fixed effects and Goodness-of-fit statistics in god_map

### ISSUE THREAD

**Issue by cmschiller** [vincentarelbundock/modelsummary#644]
When I run regressions using fixest::feols and try to summarize the results using modelsummary::modelsummary, I often want to include both indicators for the fixed effects in my foels model and goodness-of-fit statistics. The names of the fixed effects in the data are different from the way I want to display them in the table, especially when using FE-interactions, so I use a gof_map object like this:

```r
gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "FE: isin", "FE: Firm", ~fmt,
  "FE: fic^year", "FE: Country-Year", ~fmt)
```

However, when I try to also include the number of observations and R2 in 'gm' as follows, I get the following error:

```
gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "FE: isin", "FE: Firm", ~fmt,
  "FE: fic^year", "FE: Country-Year", ~fmt, 
  "nobs", "N", 0,
  "r.squared", "R2", 2)

"Error in x$raw : $ operator is invalid for atomic vectors"
```

Any help would be much appreciated!

**Comment by vincentarelbundock** [comment]
I’m very sorry for the delay. Work has been crazy, then vacation, etc.

I can’t replicate your problem. Could you install the latest version from Github, restart R and try again?

Also, make sure the `tribble` call is appropriate. In the example you gave, there are bad entries like `~fmt` instead of an integer or valid string.

When I try this, it works:

``` r
library(fixest)
library(modelsummary)

mod <- feols(mpg ~ hp | carb, data = mtcars)
gm <- tibble::tribble(
  ~raw, ~clean, ~fmt,
  "FE: carb", "Carburators", 0,
  "nobs", "N", 0
)
modelsummary(mod, gof_map = gm)
```

|             |     (1) |
| :---------- | ------: |
| hp          | \-0.071 |
|             | (0.021) |
| Carburators |       X |
| N           |      32 |
