### ISSUE TITLE
Feature request: report / plot standardized coefficients

### ISSUE THREAD

**Issue by friendly** [vincentarelbundock/modelsummary#695]
In cases where the predictor variables are on quite different scales, coefficient plots can be misleading, as I describe in https://rpubs.com/friendly/coefplots-demo 

I show there some alternatives, which essentially entail re-fitting the model to re-scaled versions of the predictors, either standardized or using more comparable units prior to plotting.

It would be nice if this could be handled internally by `modelsummary` and `modelplot` functions, say with an argument 
`standardize = TRUE` for the case of showing/plotting $\beta$ coefficients.

**Comment by friendly** [comment]
Looking over the code in `modelsummary`, perhaps a useful new argument could be

`coef_rescale` = logical (TRUE = all variables standardized; defaults to FALSE), or a numeric vector giving scale factors to be applied to the predictors)

I think the computation could be handled internally in `modelsummary` using `update()`

**Comment by vincentarelbundock** [comment]
Thanks for the feature request!

I think that what you are looking for may already be possible.

Background: `modelsummary` extracts coefficients from model objects using the `parameters` package, and that package offers several options for standardization: <https://easystats.github.io/parameters/reference/model_parameters.default.html>

We can pass the `standardize="refit"` (or other) argument directly to `modelsummary` or `modelplot`, and that argument will be forwarded to `parameters`. For example to refit the model on standardized data and plot the results. Compare to the two plots below. 


You'll see a warning because `...` is actually pushed to both `parameters` and `ggplot2`. The warning is annoying but harmless in this case.

``` r
library(modelsummary)
mod <- lm(mpg ~ hp + am, data = mtcars)

modelplot(mod, standardize = "refit")
```

![](https://i.imgur.com/iJHqh4D.png)


``` r
modelplot(mod)
```

![](https://i.imgur.com/pBNm5ED.png)

**Comment by friendly** [comment]
Thanks. `standardize = "refit"` is what I was looking for.
I didn't realize that `modelsummary` works through `parameters`

**Comment by friendly** [comment]
FYI: I updated my script to include this: https://rpubs.com/friendly/1139016

**Comment by vincentarelbundock** [comment]
This looks great!
