### ISSUE TITLE
Horizontally arranged groups based on nested lists (feature request)

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/modelsummary#715]
I know that `tab_spanner` from the gt-package and `add_header_above` from the kableExtra-package can be used to group models when multiple models are printed side-by-side (as shown here https://modelsummary.com/articles/appearance.html#kableextra). Currently, nested lists can only be printed as panels in modelsummary. However, it would be great to have the option to print them side-by-side as well. An elegant implementation for this feature could be as follows:

```r
models <- list(OLS = list(Bivariate =  lm(Girth ~ Height, data = trees),
                          Multivariate = lm(Girth ~ Height + Volume, data = trees)),
               Poisson = list(Bivariate =  glm(Girth ~ Height, family = poisson, data = trees),
                              Multivariate = glm(Girth ~ Height + Volume, family = poisson, data = trees)))


tab <- modelsummary(models, 
                    shape = term + statistic ~ model + group 
                    ) 
```

Integrating this functionality directly into modelsummary offers several advantages:

- It reduces reliance on other packages like gt and kableExtra. Particularly as modelsummary moves away from kableExtra—a change that I support—this feature would reduce the need for dependencies on additional packages in the user's code.
- A direct implementation in modelsummary would alleviate the cumbersome process of readjusting the widths of spanners each time new models are added. This task is typically laborious and not easily automated. Especially, with kableExtra, once modelsummary has run, the original table structure cannot be easily recovered in a pipe.

**Comment by vincentarelbundock** [comment]
Could you show me an example of a real-world table like what you want? I'm having a hard time visualizing it based on your description.

**Comment by vincentarelbundock** [comment]
Or do you just mean that the nested list would be flattened and call add_header_above automatically?

**Comment by MarcoPortmann** [comment]
> Or do you just mean that the nested list would be flattened and call add_header_above automatically?

Yes, this exactly what I had in mind. It is supposed to be a shortcut for this:

```r
models2 <- list(Bivariate =  lm(Girth ~ Height, data = trees),
               Multivariate = lm(Girth ~ Height + Volume, data = trees),
               Bivariate =  glm(Girth ~ Height, family = poisson, data = trees),
               Multivariate = glm(Girth ~ Height + Volume, family = poisson, data = trees))

tab <- modelsummary(models2) %>% 
  add_header_above(c(" ", "OLS" = 2, "Poisson" = 2))
```

**Comment by vincentarelbundock** [comment]
Got it.

I understand why this would be convenient for some users, but I have some hesitations, which I list below. This is not to say I'm not going to implement this, but I need to think about it...

> would reduce the need for dependencies on additional packages **in the user's code.**

I bolded the key part for me. The implementation you propose would not reduce dependencies, as the spanning labels would still drawn by external packages. What it would do is bring a feature that is currently delegated to external packages under the umbrella of `modelsummary`. It would simplify users' code, but would add a fair amount of complexity and maintenance cost to `modelsummary`.

> proposed formula interface

Frankly, I'm not convinced by the proposed syntax. My experience in teaching this stuff is that the `shape` formula syntax is already one of the hardest pieces to understand about the user interface. I'm not (yet) convinced that I want to overload it with yet more feature.

> It is supposed to be a shortcut for this:

Is it really that much of a shortcut? In version 2.0.0 `modelsummary` will use `tinytable` as its default table-drawing backend. With that package, you can easily set the bounds of the spanning label to something like `length(models)` to adjust it automatically:

```r
modelsummary(models2) %>% 
  group_tt(list("OLS" = 2:3, "Poisson" = 4:length(models2))
```

This takes about the same number of characters as your "shortcut" above.

**Comment by MarcoPortmann** [comment]
I understand the trade-off between making modelsummary more complex vs. relieving the user of work for which he could call group_tt, add_header_above etc. himself. My rationale is that modelsummary will always have the dependencies to gt, kableExtra, tinytable anyway. From this point of view, the feature would not be very costly.

I agree, the extra code for the user is not much effort in a static example with two groups and four regressions. However, with a large number of estimates and many groups that I want to easily expand or reduce in a highly automated manner, it becomes cumbersome to manually adjust the groups and ranges.  I know that automation is possible. However, it is not  trivial if you want to achieve it in an elegant way using a pipe. 

The nice thing about the way the panels are handled by modelsummary is that `models` (i.e., the number of panels or regressions) can vary arbitrarily without the need to change any other argument in modelsummary or in a function downstream.

**Comment by vincentarelbundock** [comment]
Right, that all makes sense. I’m very wary of adding more complexity, but since we already have a `shape="rbind"` option, maybe we could have a `shape="cbind"` option. This syntax:

``` r
modelsummary(models, shape = "cbind")
```

would essentially do this:

``` r
library(modelsummary)
library(tinytable)

models <- list(
    OLS = list(
        Bivariate = lm(Girth ~ Height, data = trees),
        Multivariate = lm(Girth ~ Height + Volume, data = trees)),
    Poisson = list(
        Bivariate = glm(Girth ~ Height, family = poisson, data = trees),
        Multivariate = glm(Girth ~ Height + Volume, family = poisson, data = trees)))

get_span <- function(models) {
    model_names <- rep(names(models), sapply(models, length))
    model_indices <- seq_along(model_names)
    indices_list <- split(model_indices, model_names)
    final_indices <- lapply(indices_list, function(x) range(x))
    lapply(final_indices, function(x) x + 1)
}

modelsummary(do.call(c, unname(models))) |>
    group_tt(j = get_span(models))
```

|             | OLS       |              | Poisson   |              |
|-------------|-----------|--------------|-----------|--------------|
|             | Bivariate | Multivariate | Bivariate | Multivariate |
| (Intercept) | −6.188    | 10.816       | 1.072     | 2.381        |
|             | (5.960)   | (1.973)      | (0.622)   | (0.724)      |
| Height      | 0.256     | −0.045       | 0.020     | −0.003       |
|             | (0.078)   | (0.028)      | (0.008)   | (0.010)      |
| Volume      |           | 0.195        |           | 0.013        |
|             |           | (0.011)      |           | (0.004)      |
| Num.Obs.    | 31        | 31           | 31        | 31           |
| R2          | 0.270     | 0.941        |           |              |
| R2 Adj.     | 0.244     | 0.937        |           |              |
| AIC         | 154.1     | 78.2         | 157.1     | 145.0        |
| BIC         | 158.4     | 84.0         | 160.0     | 149.3        |
| Log.Lik.    | −74.061   | −35.116      | −76.550   | −69.479      |
| F           | 10.707    | 222.471      | 6.002     | 10.382       |
| RMSE        | 2.64      | 0.75         | 2.64      | 1.01         |

**Comment by MarcoPortmann** [comment]
I agree `shape = "cbind"` may be te better solution. It is easier to understand than the formula. And the formula approach would allow for many more use cases and complexity.

**Comment by vincentarelbundock** [comment]
Thanks for the feedback.

I have now implemented the requested feature and it turned out quite nice. Thanks for the suggestion!

The feature is available now, but it requires the development versions of both `tinytable` and `modelsummary`.

```r
remotes::install_github("vincentarelbundock/tinytable")
remotes::install_github("vincentarelbundock/modelsummary")
```

Restart R, and then try the example published on the website here: https://modelsummary.com/vignettes/modelsummary.html#string-cbind-automatic-spanning-column-labels

Note that the feature is currently only implemented for the `tinytable` backend. I would be happy to review and merge a Pull Request if anyone wants to implement this for other backends. It should be easy enough to modify this file: https://github.com/vincentarelbundock/modelsummary/blob/main/R/modelsummary_cbind.R

However, for transparency, I should say that I am unlikely to implement this for other backends in the short or medium run.

**Comment by MarcoPortmann** [comment]
Thank you very much for the realization of the feature and for the `modelsummary` package in general!

I will try to give feedback in the next few days and maybe do the implementation for another backend.
