### ISSUE TITLE
Error on `vcov="bootstrap"`

### ISSUE THREAD

**Issue by joshuafayallen** [vincentarelbundock/modelsummary#744]

**Comment by joshuafayallen** [comment]
Hi Vincent, 
I keep getting this error from when using `vcov` to correct the standard errors and I keep getting this error 

``` r
library(palmerpenguins)
library(modelsummary)
#> Warning: package 'modelsummary' was built under R version 4.3.3
#> `modelsummary` 2.0.0 now uses `tinytable` as its default table-drawing
#>   backend. Learn more at: https://vincentarelbundock.github.io/tinytable/
#> 
#> Revert to `kableExtra` for one session:
#> 
#>   options(modelsummary_factory_default = 'kableExtra')
#> 
#> Change the default backend persistently:
#> 
#>   config_modelsummary(factory_default = 'gt')
#> 
#> Silence this message forever:
#> 
#>   config_modelsummary(startup_message = FALSE)


test_mod = lm(body_mass_g ~ bill_length_mm, data = penguins)


modelsummary(test_mod, vcov = 'bootstrap', cluster = 'species')
#> Error: Unable to extract a variance-covariance matrix from model of class `lm`.
```

<sup>Created on 2024-04-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Here is the `sessioninfo:

``` r
sessionInfo()
#> R version 4.3.2 (2023-10-31)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Sonoma 14.0
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> time zone: America/New_York
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.10.2     digest_0.6.35     fastmap_1.1.1     xfun_0.43        
#>  [5] magrittr_2.0.3    glue_1.7.0        R.utils_2.12.3    knitr_1.45       
#>  [9] htmltools_0.5.8   rmarkdown_2.26    lifecycle_1.0.4   cli_3.6.2        
#> [13] R.methodsS3_1.8.2 vctrs_0.6.5       reprex_2.1.0      withr_3.0.0      
#> [17] compiler_4.3.2    R.oo_1.26.0       R.cache_0.16.0    purrr_1.0.2      
#> [21] rstudioapi_0.15.0 tools_4.3.2       evaluate_0.23     yaml_2.3.8       
#> [25] rlang_1.1.3       fs_1.6.3
```

<sup>Created on 2024-04-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report!

Using the development versions of both `insight` and `modelsummary` should return a more informative error. It looks like the problem had to do with missing values. You can pass a vector instead of the name of the variable to the `cluster` argument:

``` r
remotes::install_github("easystats/insight")
remotes::install_github("vincentarelbundock/modelsummary")
```

``` r
library(palmerpenguins)
library(modelsummary)
test_mod = lm(body_mass_g ~ bill_length_mm, data = penguins)


modelsummary(test_mod, vcov = 'bootstrap', cluster = penguins$species)
```

<table style="width:42%;">
<colgroup>
<col style="width: 23%" />
<col style="width: 18%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><ol type="1">
<li></li>
</ol></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>362.307</td>
</tr>
<tr class="even">
<td></td>
<td>(1621.185)</td>
</tr>
<tr class="odd">
<td>bill_length_mm</td>
<td>87.415</td>
</tr>
<tr class="even">
<td></td>
<td>(41.620)</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>342</td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.354</td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>0.352</td>
</tr>
<tr class="even">
<td>AIC</td>
<td>5400.0</td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>5411.5</td>
</tr>
<tr class="even">
<td>Log.Lik.</td>
<td>-2696.987</td>
</tr>
<tr class="odd">
<td>RMSE</td>
<td>643.54</td>
</tr>
<tr class="even">
<td>Std.Errors</td>
<td>Bootstrap</td>
</tr>
</tbody>
</table>

**Comment by joshuafayallen** [comment]
Got it thank you so much!
