### ISSUE TITLE
`tinytable::style_tt()` does not correctly work in Quarto revealjs

### ISSUE THREAD

**Issue by kazuyanagimoto** [vincentarelbundock/modelsummary#759]
Hi @vincentarelbundock !
I want to use `tinytable::style_tt()` in the Quarto revealjs slides to highlight lines one by one but encountered unexpected results. Here is a small example.

````markdown
---
format: revealjs
execute:
  echo: false
---

## Page 1

```{r}
library(modelsummary)
library(tinytable)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list(
  "OLS 1"     = lm(Donations ~ Literacy + Clergy, data = dat),
  "Poisson" = glm(Donations ~ Literacy + Commerce, family = poisson, data = dat),
  "OLS 2"     = lm(Crime_pers ~ Literacy + Clergy, data = dat)
)

tt_mdl <- modelsummary(models)
tt_mdl
```

## Page 2

```{r}
tt_mdl |>
  style_tt(i = 3, background = "skyblue")
```

## Page 3

```{r}
tt_mdl |>
  style_tt(i = 5, background = "orange")
```

````

- **Expected Behavior**: Page 1 shows the original regression table. Page 2 highlights the 3rd line and Page 3 does the 5th line.
- **Actual Behavior**: Page 1 & 2 shows barebone table (no style for lines and not center aligned) and Page 3 show the two highlighted lines at once.
- It does not happen if I only use `tinytable` but does not use `modelsummary`

**Version info**

- OS: Windows 11 & Ubuntu 22.04
- R: 4.4.0
- Quarto: 1.4.553
- tinytable: 0.2.1
- modelsummary: 2.0.0

**Comment by vincentarelbundock** [comment]
Thanks for the report!

Could you please install version 0.2.1.14 of `tinytable` from Github, restart R, and try again?

**Comment by kazuyanagimoto** [comment]
It seems that the issue has been solved.
Thank you for your quick fix!

**Comment by vincentarelbundock** [comment]
Sorry @kazuyanagimoto but there's a very good chance I'll need to revert this change, as it creates a ton of problems under in other contexts.

The problem is that `style_tt()` inserts javascript functions in the document, and that those functions must specify a table object ID. If multiple functions are tied to the same ID, the preceding styles changes remain or conflict with new ones. If the table-level IDs are reset every time we call `style_tt()`, then that causes a ton of problems with other functions that call `style_tt()` under the hood (ex: to style bottom lines and groups).

I can't think of a good solution on `tinytable` end. The solution for users is to create an all new table on every slide, by calling `modelsummary()` in a hidden code chunk and reassining the table object on every slide.

**Comment by vincentarelbundock** [comment]
Oh, I just thought of a simpler solution and will document it in the `tinytable` FAQ:

https://github.com/vincentarelbundock/tinytable/pull/304/commits/c1608aaac27ef333b9e9b5c92b37b3923ff89adc
