### ISSUE TITLE
Pre-set aesthetics for tables

### ISSUE THREAD

**Issue by Chris-Larkin** [vincentarelbundock/modelsummary#777]
modelsummary is clearly an impressive and highly customizable function. For me, and I suspect this is true for a lot of [would-be] users, i don't want to have customize though; i just want the package to work. I appreciate this might sound a bit entitled but it'd great if a user could output tables in stargazer's classic format, for example, or per various journals' formatting guidelines. My sense is this will significantly improve ease of adoption. 

Some more specific things i'd love to be able to do but can't find a way to (yet): 

* move a regression intercept to the bottom of the table
* change the font to Times New Roman
* change the white space padding around individual cells
* output the table inline as ASCII (i mostly code interactively using rmarkdown files)
* justify the note on the bottom right

Just some thoughts. I do not have the technical skill to write PRs for these items; i'm (mostly) just a humble user. Thanks for all your work

**Comment by vincentarelbundock** [comment]
Hi,

You can move the intercept to the bottom using coef_map.

The font should be changed in the document. I consider it bad practice to change this setting at the table level, because documents and tables get different fonts.

The white space can be controlled by the table drawing package. For instance, if you use tinytable (the default) you can read that package documentation to figure out how to change padding. Same for gt, kableExtra, etc.

You can get ASCII tables with output="markdown". The document explains how to set a global option to make that default.

There is already support for themes. In my experience, tables are much less standardized than wed think within publishers and journals. So it is difficult to implement themes. I'll be happy to consider submissions if someone makes one. 

FWIW, I mildly dislike the stargazer defaults, so I will not implement that team, but might be open to contributions.

**Comment by Chris-Larkin** [comment]
Thanks for this. I'll see what I can do about building a custom theme. 

And that's fair on stargazer defaults.
