### ISSUE TITLE
Stars in documentation should be escaped

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#797]
Probably an `altdoc` issue but I report it here first.

In `.Rd` file:

https://github.com/vincentarelbundock/modelsummary/blob/ee9b2f2a4829b3dfac73ebb5464c062fcba3d77e/man/modelsummary.Rd#L137-L140

On website:

![image](https://github.com/user-attachments/assets/2d86a335-d640-4387-b319-a0805176a581)

**Comment by vincentarelbundock** [comment]
Hmm, yes. I tried escaping a couple different ways and can't figure out how to fix this...

**Comment by etiennebacher** [comment]
Would it help to put them in code formatting (like the last bullet point)?

**Comment by vincentarelbundock** [comment]
that's what I tried here: https://github.com/vincentarelbundock/modelsummary/commit/5b3b42aafdf60253d669d12cb88941c374e1508e

and the current website doesn't look great: https://modelsummary.com/man/modelsummary.html#arguments

**Comment by vincentarelbundock** [comment]
Looks like this may be a Quarto issue. After calling `altdoc:::.rd2qmd`, we get a document with this line:

```r
<li> TRUE: <code>c("+" = .1, "*" = .05, "**" = .01, "***" = 0.001)</code>
```

To me, this looks like what we want. So the problem comes up when creating the website from individual .qmd files.

I think this may be hard to diagnose and fix. Since any fix won't happen in `modelsummary`, I'll close this issue.
