### ISSUE TITLE
Issue when using coef_map and more than one statistic

### ISSUE THREAD

**Issue by sbw78** [vincentarelbundock/modelsummary#88]
When I try to rename coefficients while also reporting more than one statistic (e.g., std.error and conf.int), I get the following error:

``` r
cm <- c("(Intercept)" = "Intercept",
        "factor(cyl)6" = "6-cylinder",
        "factor(cyl)8" = "8-cylinder")
models <- list()
models[['OLS']] <- lm(mpg ~ factor(cyl), mtcars)
models[['Logit']] <- glm(am ~ factor(cyl), mtcars, family = binomial)

rows <- tibble::tribble(~term,          ~OLS,  ~Logit, ~section, ~position,
                'factor(cyl)4', '-',   '-',    'middle', 4)
modelsummary::msummary(models, statistic = c('std.error', 'conf.int'),
                       coef_map = cm,
                       add_rows = rows)
#> Error in modelsummary::extract(models, statistic = statistic, statistic_override = statistic_override, : You are trying to assign the same name to two different variables in model 1
```
<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Works fine when I only use one item for `statistic`.

``` r
cm <- c("(Intercept)" = "Intercept",
        "factor(cyl)6" = "6-cylinder",
        "factor(cyl)8" = "8-cylinder")
models <- list()
models[['OLS']] <- lm(mpg ~ factor(cyl), mtcars)
models[['Logit']] <- glm(am ~ factor(cyl), mtcars, family = binomial)

rows <- tibble::tribble(~term,          ~OLS,  ~Logit, ~section, ~position,
                'factor(cyl)4', '-',   '-',    'middle', 3)
modelsummary::msummary(models, statistic = c('std.error'),
                       style = "markdown",
                       coef_map = cm,
                       add_rows = rows)
```

<div id="gippixnrkd" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

OLS

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

Logit

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Intercept

</td>

<td class="gt_row gt_left">

26.664

</td>

<td class="gt_row gt_left">

0.981

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(0.972)

</td>

<td class="gt_row gt_left">

(0.677)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

factor(cyl)4

</td>

<td class="gt_row gt_left">

\-

</td>

<td class="gt_row gt_left">

\-

</td>

</tr>

<tr>

<td class="gt_row gt_left">

6-cylinder

</td>

<td class="gt_row gt_left">

\-6.921

</td>

<td class="gt_row gt_left">

\-1.269

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(1.558)

</td>

<td class="gt_row gt_left">

(1.021)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

8-cylinder

</td>

<td class="gt_row gt_left">

\-11.564

</td>

<td class="gt_row gt_left">

\-2.773

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

(1.299)

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

(1.021)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Num.Obs.

</td>

<td class="gt_row gt_left">

32

</td>

<td class="gt_row gt_left">

32

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2

</td>

<td class="gt_row gt_left">

0.732

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2 Adj.

</td>

<td class="gt_row gt_left">

0.714

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

AIC

</td>

<td class="gt_row gt_left">

170.6

</td>

<td class="gt_row gt_left">

39.9

</td>

</tr>

<tr>

<td class="gt_row gt_left">

BIC

</td>

<td class="gt_row gt_left">

176.4

</td>

<td class="gt_row gt_left">

44.3

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Log.Lik.

</td>

<td class="gt_row gt_left">

\-81.282

</td>

<td class="gt_row gt_left">

\-16.967

</td>

</tr>

</tbody>

</table>

</div>

<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report! This was an easy fix. I also included a test to make sure it doesn't happen again. 

This is an important bug, and it needs to be fixed, but I'm probably going to wait a bit before uploading to CRAN because I'm preparing a major release with some big new features. In the meantime, you can install from Github to get a working version.


Here's part of the code I'm using in the test:


``` r
library(modelsummary)
cm <- c("(Intercept)" = "Intercept",
        "factor(cyl)6" = "6-cylinder",
        "factor(cyl)8" = "8-cylinder")
models <- list()
models[['OLS']] <- lm(mpg ~ factor(cyl), mtcars)
models[['Logit']] <- glm(am ~ factor(cyl), mtcars, family = binomial)
rows <- tibble::tribble(
    ~term,        ~OLS, ~Logit, ~section, ~position,
    '4-cylinder', '-',  '-',    'middle', 4,
    '12-cylinder', '-',  '-',    'middle', 5)
modelsummary(models, 
             statistic = c('std.error', 'conf.int'), 
             add_rows = rows, 
             coef_map = cm)
```





<div id="jlcrklggdu" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

OLS

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

Logit

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Intercept

</td>

<td class="gt_row gt_left">

26.664

</td>

<td class="gt_row gt_left">

0.981

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(0.972)

</td>

<td class="gt_row gt_left">

(0.677)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

\[24.676, 28.651\]

</td>

<td class="gt_row gt_left">

\[-0.260, 2.499\]

</td>

</tr>

<tr>

<td class="gt_row gt_left">

4-cylinder

</td>

<td class="gt_row gt_left">

\-

</td>

<td class="gt_row gt_left">

\-

</td>

</tr>

<tr>

<td class="gt_row gt_left">

12-cylinder

</td>

<td class="gt_row gt_left">

\-

</td>

<td class="gt_row gt_left">

\-

</td>

</tr>

<tr>

<td class="gt_row gt_left">

6-cylinder

</td>

<td class="gt_row gt_left">

\-6.921

</td>

<td class="gt_row gt_left">

\-1.269

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(1.558)

</td>

<td class="gt_row gt_left">

(1.021)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

\[-10.108, -3.734\]

</td>

<td class="gt_row gt_left">

\[-3.405, 0.689\]

</td>

</tr>

<tr>

<td class="gt_row gt_left">

8-cylinder

</td>

<td class="gt_row gt_left">

\-11.564

</td>

<td class="gt_row gt_left">

\-2.773

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(1.299)

</td>

<td class="gt_row gt_left">

(1.021)

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

\[-14.220, -8.908\]

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

\[-5.045, -0.933\]

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Num.Obs.

</td>

<td class="gt_row gt_left">

32

</td>

<td class="gt_row gt_left">

32

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2

</td>

<td class="gt_row gt_left">

0.732

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2 Adj.

</td>

<td class="gt_row gt_left">

0.714

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

AIC

</td>

<td class="gt_row gt_left">

170.6

</td>

<td class="gt_row gt_left">

39.9

</td>

</tr>

<tr>

<td class="gt_row gt_left">

BIC

</td>

<td class="gt_row gt_left">

176.4

</td>

<td class="gt_row gt_left">

44.3

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Log.Lik.

</td>

<td class="gt_row gt_left">

\-81.282

</td>

<td class="gt_row gt_left">

\-16.967

</td>

</tr>

</tbody>

</table>

</div>



<sup>Created on 2020-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sbw78** [comment]
Awesome, thank you for fixing this so quickly! I'm already using the github version, so I'll update the package and give it a go. Thanks!

**Comment by vincentarelbundock** [comment]
Excellent!

**Comment by vincentarelbundock** [comment]
FYI, I need to change the user interface for `add_rows`, because I want to introduce an `add_columns` option and need to ensure that the two arguments behave similarly. The position of rows is now determined by an attribute. Here's the equivalent of your code from above:

library(tidyverse)

cm <- c("(Intercept)" = "Intercept",
        "factor(cyl)6" = "6-cylinder",
        "factor(cyl)8" = "8-cylinder")
models <- list()
models[['OLS']] <- lm(mpg ~ factor(cyl), mtcars)
models[['Logit']] <- glm(am ~ factor(cyl), mtcars, family = binomial)

# additional row is a data.frame with the same number of columns as your table. The column names don't matter anymore. it is just a `rbind`
rows <- tibble::tribble(~X1,            ~X2, ~X3,
                        'factor(cyl)4', '-', '-',
                        'New GOF',      '?', '?')

# defining row positions
attr(rows, 'position') <- c(4, 11)

modelsummary::msummary(models, statistic = c('std.error', 'conf.int'),
                       coef_map = cm,
                       add_rows = rows)
